import { sql } from "drizzle-orm";
import { boolean, check, foreignKey, index, jsonb, pgTable, primaryKey, text, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { instant } from "./columns";
import { governorates, cities, zones } from "./geography";
import { mainCategories, subcategories } from "./catalog";
import { stores, storeCategories } from "./stores";
import { products, productSizes } from "./products";
import { modifierGroups, modifierOptions } from "./modifiers";

export const supportedLocales = pgTable("supported_locales", {
  code: text("code").primaryKey(),
  nativeName: text("native_name").notNull(),
  direction: text("direction").notNull(),
  fallbackLocale: text("fallback_locale"),
  isActive: boolean("is_active").notNull().default(true),
  isDefault: boolean("is_default").notNull().default(false),
  requiredForNewContent: boolean("required_for_new_content").notNull().default(false),
  createdAt: instant("created_at").notNull().defaultNow(),
  updatedAt: instant("updated_at").notNull().defaultNow(),
}, (table) => [
  foreignKey({ columns: [table.fallbackLocale], foreignColumns: [table.code] }),
  uniqueIndex("supported_locales_one_default_uidx").on(table.isDefault).where(sql`${table.isDefault} = true`),
  check("supported_locales_code_chk", sql`${table.code} ~ '^[a-z]{2,3}(-[a-z0-9]{2,8})*$'`),
  check("supported_locales_direction_chk", sql`${table.direction} in ('LTR','RTL')`),
  check("supported_locales_fallback_self_chk", sql`${table.fallbackLocale} is null or ${table.fallbackLocale} <> ${table.code}`),
  check("supported_locales_default_active_chk", sql`${table.isDefault} = false or ${table.isActive} = true`),
  check("supported_locales_required_active_chk", sql`${table.requiredForNewContent} = false or ${table.isActive} = true`),
]);

const timestamps = { createdAt: instant("created_at").notNull().defaultNow(), updatedAt: instant("updated_at").notNull().defaultNow() };

export const governorateTranslations = pgTable("governorate_translations", { governorateId: uuid("governorate_id").notNull().references(() => governorates.id, { onDelete: "cascade" }), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), ...timestamps }, (t) => [primaryKey({ columns: [t.governorateId, t.locale] }), index("governorate_translations_locale_name_idx").on(t.locale, t.name), check("governorate_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const cityTranslations = pgTable("city_translations", { cityId: uuid("city_id").notNull().references(() => cities.id, { onDelete: "cascade" }), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), ...timestamps }, (t) => [primaryKey({ columns: [t.cityId, t.locale] }), index("city_translations_locale_name_idx").on(t.locale, t.name), check("city_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const zoneTranslations = pgTable("zone_translations", { zoneId: uuid("zone_id").notNull().references(() => zones.id, { onDelete: "cascade" }), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.zoneId, t.locale] }), foreignKey({ columns: [t.zoneId, t.cityId], foreignColumns: [zones.id, zones.cityId] }), uniqueIndex("zone_translations_city_name_active_uidx").on(t.cityId, t.locale, sql`lower(btrim(${t.name}))`).where(sql`${t.archivedAt} is null`), index("zone_translations_city_locale_name_idx").on(t.cityId, t.locale, t.name), check("zone_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const mainCategoryTranslations = pgTable("main_category_translations", { mainCategoryId: uuid("main_category_id").notNull().references(() => mainCategories.id, { onDelete: "cascade" }), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.mainCategoryId, t.locale] }), foreignKey({ columns: [t.mainCategoryId, t.cityId], foreignColumns: [mainCategories.id, mainCategories.cityId] }), uniqueIndex("main_category_translations_city_name_active_uidx").on(t.cityId, t.locale, sql`lower(btrim(${t.name}))`).where(sql`${t.archivedAt} is null`), index("main_category_translations_city_locale_name_idx").on(t.cityId, t.locale, t.name), check("main_category_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const subcategoryTranslations = pgTable("subcategory_translations", { subcategoryId: uuid("subcategory_id").notNull().references(() => subcategories.id, { onDelete: "cascade" }), cityId: uuid("city_id").notNull(), mainCategoryId: uuid("main_category_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.subcategoryId, t.locale] }), foreignKey({ columns: [t.subcategoryId, t.mainCategoryId, t.cityId], foreignColumns: [subcategories.id, subcategories.mainCategoryId, subcategories.cityId] }), uniqueIndex("subcategory_translations_parent_name_active_uidx").on(t.cityId, t.mainCategoryId, t.locale, sql`lower(btrim(${t.name}))`).where(sql`${t.archivedAt} is null`), index("subcategory_translations_city_locale_name_idx").on(t.cityId, t.locale, t.name), check("subcategory_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const storeTranslations = pgTable("store_translations", { storeId: uuid("store_id").notNull().references(() => stores.id, { onDelete: "cascade" }), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), address: text("address").notNull(), ...timestamps }, (t) => [primaryKey({ columns: [t.storeId, t.locale] }), foreignKey({ columns: [t.storeId, t.cityId], foreignColumns: [stores.id, stores.cityId] }), index("store_translations_city_locale_name_idx").on(t.cityId, t.locale, t.name), check("store_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`), check("store_translations_address_nonempty_chk", sql`length(btrim(${t.address})) > 0`)]);
export const storeCategoryTranslations = pgTable("store_category_translations", { storeCategoryId: uuid("store_category_id").notNull().references(() => storeCategories.id, { onDelete: "cascade" }), storeId: uuid("store_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.storeCategoryId, t.locale] }), foreignKey({ columns: [t.storeCategoryId, t.storeId], foreignColumns: [storeCategories.id, storeCategories.storeId] }), index("store_category_translations_store_locale_name_idx").on(t.storeId, t.locale, t.name), check("store_category_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const productTranslations = pgTable("product_translations", { productId: uuid("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), storeId: uuid("store_id").notNull(), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), description: text("description"), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.productId, t.locale] }), foreignKey({ columns: [t.productId, t.storeId, t.cityId], foreignColumns: [products.id, products.storeId, products.cityId] }), index("product_translations_store_locale_name_idx").on(t.storeId, t.locale, t.name), check("product_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const productSizeTranslations = pgTable("product_size_translations", { productSizeId: uuid("product_size_id").notNull().references(() => productSizes.id, { onDelete: "cascade" }), productId: uuid("product_id").notNull(), storeId: uuid("store_id").notNull(), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.productSizeId, t.locale] }), foreignKey({ columns: [t.productSizeId, t.productId, t.storeId, t.cityId], foreignColumns: [productSizes.id, productSizes.productId, productSizes.storeId, productSizes.cityId] }), index("product_size_translations_product_locale_name_idx").on(t.productId, t.locale, t.name), check("product_size_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const modifierGroupTranslations = pgTable("modifier_group_translations", { modifierGroupId: uuid("modifier_group_id").notNull().references(() => modifierGroups.id, { onDelete: "cascade" }), storeId: uuid("store_id").notNull(), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.modifierGroupId, t.locale] }), foreignKey({ columns: [t.modifierGroupId, t.storeId, t.cityId], foreignColumns: [modifierGroups.id, modifierGroups.storeId, modifierGroups.cityId] }), index("modifier_group_translations_store_locale_name_idx").on(t.storeId, t.locale, t.name), check("modifier_group_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);
export const modifierOptionTranslations = pgTable("modifier_option_translations", { modifierOptionId: uuid("modifier_option_id").notNull().references(() => modifierOptions.id, { onDelete: "cascade" }), storeId: uuid("store_id").notNull(), cityId: uuid("city_id").notNull(), locale: text("locale").notNull().references(() => supportedLocales.code), name: text("name").notNull(), archivedAt: instant("archived_at"), ...timestamps }, (t) => [primaryKey({ columns: [t.modifierOptionId, t.locale] }), foreignKey({ columns: [t.modifierOptionId, t.storeId, t.cityId], foreignColumns: [modifierOptions.id, modifierOptions.storeId, modifierOptions.cityId] }), index("modifier_option_translations_store_locale_name_idx").on(t.storeId, t.locale, t.name), check("modifier_option_translations_name_nonempty_chk", sql`length(btrim(${t.name})) > 0`)]);

export type LocalizedMap = Record<string, string>;
export const localizedSnapshot = jsonb("localized_snapshot").$type<LocalizedMap>();
