import { Elysia, t } from "elysia";
import type { AuthModule } from "../auth-module";
import { dashboardContext } from "../core/context";
import { bearer, deviceFields, errorResponse, ipOf, parseAuthenticationBody, refreshBody, requestIdOf, revokedResponse, sessionResponse, sessionsResponse, standardErrors } from "../http/shared";
const tag = ["Dashboard — Authentication"];
export const dashboardAuthRoutes = (auth: AuthModule) => new Elysia({ prefix: "/api/v1/dashboard/auth" })
  .onParse(parseAuthenticationBody)
  .post("/login", ({ body, request, set, server }) => auth.dashboard.login({ email: body.email, password: body.password, ...(body.device_id ? { deviceId: body.device_id } : {}), deviceName: body.device_name, ip: ipOf(request, server), requestId: requestIdOf(set) }), { body: t.Object({ email: t.String({ maxLength: 254 }), password: t.String({ minLength: 12, maxLength: 128 }), ...deviceFields }, { additionalProperties: false }), response: { 200: sessionResponse, ...standardErrors }, detail: { tags: tag, summary: "Dashboard password login" } })
  .post("/token/refresh", ({ body, request, set, server }) => auth.sessions.refresh(body.refresh_token, dashboardContext, ipOf(request, server), requestIdOf(set)), { body: refreshBody, response: { 200: sessionResponse, ...standardErrors }, detail: { tags: tag } })
  .post("/logout", async ({ request, set }) => { const id = requestIdOf(set); await auth.sessions.logout(await auth.sessions.identify(bearer(request), dashboardContext), dashboardContext, id); return { revoked: true, request_id: id }; }, { response: { 200: revokedResponse, ...standardErrors }, detail: { tags: tag, security: [{ bearerAuth: [] }] } })
  .post("/logout-all", async ({ request, set }) => { const id = requestIdOf(set); await auth.sessions.logoutAll(await auth.sessions.identify(bearer(request), dashboardContext), dashboardContext, id); return { revoked: true, request_id: id }; }, { response: { 200: revokedResponse, ...standardErrors }, detail: { tags: tag, security: [{ bearerAuth: [] }] } })
  .get("/sessions", async ({ request, set }) => ({ sessions: await auth.sessions.list(await auth.sessions.authenticate(bearer(request), dashboardContext, requestIdOf(set)), dashboardContext) }), { response: { 200: sessionsResponse, ...standardErrors }, detail: { tags: tag, security: [{ bearerAuth: [] }] } })
  .delete("/sessions/:sessionId", async ({ request, set, params }) => { const id = requestIdOf(set); await auth.sessions.revoke(await auth.sessions.authenticate(bearer(request), dashboardContext, id), params.sessionId, dashboardContext, id); return { revoked: true, request_id: id }; }, { params: t.Object({ sessionId: t.String({ format: "uuid" }) }, { additionalProperties: false }), response: { 200: revokedResponse, 404: errorResponse, ...standardErrors }, detail: { tags: tag, security: [{ bearerAuth: [] }] } });
