CREATE TABLE "governorate_translations" ("governorate_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "governorate_translations_pk" PRIMARY KEY ("governorate_id", "locale"), CONSTRAINT "governorate_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "governorate_translations" ADD CONSTRAINT "governorate_translations_governorate_fk" FOREIGN KEY ("governorate_id") REFERENCES "public"."governorates"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "governorate_translations" ADD CONSTRAINT "governorate_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "governorate_translations_locale_name_idx" ON "governorate_translations" ("locale", "name");--> statement-breakpoint
INSERT INTO "governorate_translations" ("governorate_id", "locale", "name") SELECT "id", 'ar', "name_ar" FROM "governorates";--> statement-breakpoint
INSERT INTO "governorate_translations" ("governorate_id", "locale", "name") SELECT "id", 'en', "name_en" FROM "governorates";--> statement-breakpoint
CREATE TABLE "city_translations" ("city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "city_translations_pk" PRIMARY KEY ("city_id", "locale"), CONSTRAINT "city_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "city_translations" ADD CONSTRAINT "city_translations_city_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "city_translations" ADD CONSTRAINT "city_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "city_translations_locale_name_idx" ON "city_translations" ("locale", "name");--> statement-breakpoint
INSERT INTO "city_translations" ("city_id", "locale", "name") SELECT "id", 'ar', "name_ar" FROM "cities";--> statement-breakpoint
INSERT INTO "city_translations" ("city_id", "locale", "name") SELECT "id", 'en', "name_en" FROM "cities";--> statement-breakpoint
CREATE TABLE "zone_translations" ("zone_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "zone_translations_pk" PRIMARY KEY ("zone_id", "locale"), CONSTRAINT "zone_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "zone_translations" ADD CONSTRAINT "zone_translations_zone_fk" FOREIGN KEY ("zone_id", "city_id") REFERENCES "public"."zones"("id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zone_translations" ADD CONSTRAINT "zone_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "zone_translations_city_name_active_uidx" ON "zone_translations" ("city_id", "locale", lower(btrim("name"))) WHERE "archived_at" IS NULL;--> statement-breakpoint
CREATE INDEX "zone_translations_city_locale_name_idx" ON "zone_translations" ("city_id", "locale", "name");--> statement-breakpoint
INSERT INTO "zone_translations" ("zone_id", "city_id", "locale", "name", "archived_at") SELECT "id", "city_id", 'ar', "name", "archived_at" FROM "zones";
