CREATE TABLE "main_category_translations" ("main_category_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "main_category_translations_pk" PRIMARY KEY ("main_category_id", "locale"), CONSTRAINT "main_category_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "main_category_translations" ADD CONSTRAINT "main_category_translations_category_fk" FOREIGN KEY ("main_category_id", "city_id") REFERENCES "public"."main_categories"("id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "main_category_translations" ADD CONSTRAINT "main_category_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "main_category_translations_city_name_active_uidx" ON "main_category_translations" ("city_id", "locale", lower(btrim("name"))) WHERE "archived_at" IS NULL;--> statement-breakpoint
CREATE INDEX "main_category_translations_city_locale_name_idx" ON "main_category_translations" ("city_id", "locale", "name");--> statement-breakpoint
INSERT INTO "main_category_translations" ("main_category_id", "city_id", "locale", "name", "archived_at") SELECT "id", "city_id", 'ar', "name", "archived_at" FROM "main_categories";--> statement-breakpoint
CREATE TABLE "subcategory_translations" ("subcategory_id" uuid NOT NULL, "city_id" uuid NOT NULL, "main_category_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "subcategory_translations_pk" PRIMARY KEY ("subcategory_id", "locale"), CONSTRAINT "subcategory_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "subcategory_translations" ADD CONSTRAINT "subcategory_translations_category_fk" FOREIGN KEY ("subcategory_id", "main_category_id", "city_id") REFERENCES "public"."subcategories"("id", "main_category_id", "city_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "subcategory_translations" ADD CONSTRAINT "subcategory_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "subcategory_translations_parent_name_active_uidx" ON "subcategory_translations" ("city_id", "main_category_id", "locale", lower(btrim("name"))) WHERE "archived_at" IS NULL;--> statement-breakpoint
CREATE INDEX "subcategory_translations_city_locale_name_idx" ON "subcategory_translations" ("city_id", "locale", "name");--> statement-breakpoint
INSERT INTO "subcategory_translations" ("subcategory_id", "city_id", "main_category_id", "locale", "name", "archived_at") SELECT "id", "city_id", "main_category_id", 'ar', "name", "archived_at" FROM "subcategories";
