CREATE TABLE "store_translations" ("store_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "address" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "store_translations_pk" PRIMARY KEY ("store_id", "locale"), CONSTRAINT "store_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0), CONSTRAINT "store_translations_address_nonempty_chk" CHECK (length(btrim("address")) > 0));--> statement-breakpoint
ALTER TABLE "store_translations" ADD CONSTRAINT "store_translations_store_fk" FOREIGN KEY ("store_id", "city_id") REFERENCES "public"."stores"("id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_translations" ADD CONSTRAINT "store_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "store_translations_city_locale_name_idx" ON "store_translations" ("city_id", "locale", "name");--> statement-breakpoint
INSERT INTO "store_translations" ("store_id", "city_id", "locale", "name", "address") SELECT "id", "city_id", 'ar', "name", "address" FROM "stores";--> statement-breakpoint
CREATE TABLE "store_category_translations" ("store_category_id" uuid NOT NULL, "store_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "store_category_translations_pk" PRIMARY KEY ("store_category_id", "locale"), CONSTRAINT "store_category_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "store_category_translations" ADD CONSTRAINT "store_category_translations_category_fk" FOREIGN KEY ("store_category_id", "store_id") REFERENCES "public"."store_categories"("id", "store_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "store_category_translations" ADD CONSTRAINT "store_category_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "store_category_translations_store_locale_name_idx" ON "store_category_translations" ("store_id", "locale", "name");--> statement-breakpoint
INSERT INTO "store_category_translations" ("store_category_id", "store_id", "locale", "name", "archived_at") SELECT "id", "store_id", 'ar', "name", "archived_at" FROM "store_categories";--> statement-breakpoint
CREATE TABLE "product_translations" ("product_id" uuid NOT NULL, "store_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "description" text, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "product_translations_pk" PRIMARY KEY ("product_id", "locale"), CONSTRAINT "product_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "product_translations" ADD CONSTRAINT "product_translations_product_fk" FOREIGN KEY ("product_id", "store_id", "city_id") REFERENCES "public"."products"("id", "store_id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_translations" ADD CONSTRAINT "product_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "product_translations_store_locale_name_idx" ON "product_translations" ("store_id", "locale", "name");--> statement-breakpoint
INSERT INTO "product_translations" ("product_id", "store_id", "city_id", "locale", "name", "description", "archived_at") SELECT "id", "store_id", "city_id", 'ar', "name", "description", "archived_at" FROM "products";--> statement-breakpoint
CREATE TABLE "product_size_translations" ("product_size_id" uuid NOT NULL, "product_id" uuid NOT NULL, "store_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "product_size_translations_pk" PRIMARY KEY ("product_size_id", "locale"), CONSTRAINT "product_size_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "product_size_translations" ADD CONSTRAINT "product_size_translations_size_fk" FOREIGN KEY ("product_size_id", "product_id", "store_id", "city_id") REFERENCES "public"."product_sizes"("id", "product_id", "store_id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_size_translations" ADD CONSTRAINT "product_size_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "product_size_translations_product_locale_name_idx" ON "product_size_translations" ("product_id", "locale", "name");--> statement-breakpoint
INSERT INTO "product_size_translations" ("product_size_id", "product_id", "store_id", "city_id", "locale", "name", "archived_at") SELECT "id", "product_id", "store_id", "city_id", 'ar', "name", "archived_at" FROM "product_sizes";
