CREATE TABLE "modifier_group_translations" ("modifier_group_id" uuid NOT NULL, "store_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "modifier_group_translations_pk" PRIMARY KEY ("modifier_group_id", "locale"), CONSTRAINT "modifier_group_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "modifier_group_translations" ADD CONSTRAINT "modifier_group_translations_group_fk" FOREIGN KEY ("modifier_group_id", "store_id", "city_id") REFERENCES "public"."modifier_groups"("id", "store_id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "modifier_group_translations" ADD CONSTRAINT "modifier_group_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "modifier_group_translations_store_locale_name_idx" ON "modifier_group_translations" ("store_id", "locale", "name");--> statement-breakpoint
INSERT INTO "modifier_group_translations" ("modifier_group_id", "store_id", "city_id", "locale", "name", "archived_at") SELECT "id", "store_id", "city_id", 'ar', "name", "archived_at" FROM "modifier_groups";--> statement-breakpoint
CREATE TABLE "modifier_option_translations" ("modifier_option_id" uuid NOT NULL, "store_id" uuid NOT NULL, "city_id" uuid NOT NULL, "locale" text NOT NULL, "name" text NOT NULL, "archived_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "modifier_option_translations_pk" PRIMARY KEY ("modifier_option_id", "locale"), CONSTRAINT "modifier_option_translations_name_nonempty_chk" CHECK (length(btrim("name")) > 0));--> statement-breakpoint
ALTER TABLE "modifier_option_translations" ADD CONSTRAINT "modifier_option_translations_option_fk" FOREIGN KEY ("modifier_option_id", "store_id", "city_id") REFERENCES "public"."modifier_options"("id", "store_id", "city_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "modifier_option_translations" ADD CONSTRAINT "modifier_option_translations_locale_fk" FOREIGN KEY ("locale") REFERENCES "public"."supported_locales"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "modifier_option_translations_store_locale_name_idx" ON "modifier_option_translations" ("store_id", "locale", "name");--> statement-breakpoint
INSERT INTO "modifier_option_translations" ("modifier_option_id", "store_id", "city_id", "locale", "name", "archived_at") SELECT "id", "store_id", "city_id", 'ar', "name", "archived_at" FROM "modifier_options";--> statement-breakpoint
ALTER TABLE "cart_items" ADD COLUMN "product_name_snapshot_localized" jsonb;--> statement-breakpoint
ALTER TABLE "cart_items" ADD COLUMN "selected_size_name_snapshot_localized" jsonb;--> statement-breakpoint
ALTER TABLE "cart_item_modifier_selections" ADD COLUMN "option_name_snapshot_localized" jsonb;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "product_name_snapshot_localized" jsonb;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "selected_size_name_snapshot_localized" jsonb;--> statement-breakpoint
ALTER TABLE "order_item_replacements" ADD COLUMN "original_product_name_snapshot_localized" jsonb;--> statement-breakpoint
ALTER TABLE "order_item_replacements" ADD COLUMN "replacement_product_name_snapshot_localized" jsonb;--> statement-breakpoint
UPDATE "cart_items" SET "product_name_snapshot_localized" = jsonb_build_object('ar', "product_name_snapshot"), "selected_size_name_snapshot_localized" = CASE WHEN "selected_size_name_snapshot" IS NULL THEN NULL ELSE jsonb_build_object('ar', "selected_size_name_snapshot") END;--> statement-breakpoint
UPDATE "cart_item_modifier_selections" SET "option_name_snapshot_localized" = jsonb_build_object('ar', "option_name_snapshot");--> statement-breakpoint
UPDATE "order_items" SET "product_name_snapshot_localized" = jsonb_build_object('ar', "product_name_snapshot"), "selected_size_name_snapshot_localized" = CASE WHEN "selected_size_name_snapshot" IS NULL THEN NULL ELSE jsonb_build_object('ar', "selected_size_name_snapshot") END;--> statement-breakpoint
UPDATE "order_item_replacements" SET "original_product_name_snapshot_localized" = jsonb_build_object('ar', "original_product_name_snapshot"), "replacement_product_name_snapshot_localized" = jsonb_build_object('ar', "replacement_product_name_snapshot");--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_product_name_snapshot_localized_chk" CHECK ("product_name_snapshot_localized" IS NULL OR jsonb_typeof("product_name_snapshot_localized") = 'object' AND "product_name_snapshot_localized" ? 'ar');--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_name_snapshot_localized_chk" CHECK ("product_name_snapshot_localized" IS NULL OR jsonb_typeof("product_name_snapshot_localized") = 'object' AND "product_name_snapshot_localized" ? 'ar');
