import { Elysia, t } from "elysia";
import type { AuthModule } from "../auth/auth-module";
import { requirePublicCityContext } from "../auth/city/public-city-context";
import { customerContext, dashboardContext } from "../auth/core/context";
import { errorResponse, standardErrors } from "../auth/http/shared";
import { authIdentity, requestIdOf } from "../geography/shared";
import type { DeliveryPricingService } from "./delivery-pricing.service";

const uuid=t.String({format:"uuid"});
const pricingInput=t.Object({baseFee:t.Integer({minimum:0}),includedDistanceMeters:t.Integer({minimum:0}),pricePerKm:t.Integer({minimum:0}),roundingStep:t.Integer({minimum:1}),maximumDeliveryDistanceMeters:t.Nullable(t.Integer({minimum:1})),routingFallbackEnabled:t.Boolean(),fallbackOnNoRoute:t.Boolean(),fallbackOnProviderFailure:t.Boolean(),fallbackExtraDistanceMeters:t.Integer({minimum:0})},{additionalProperties:false});
const pricing=t.Intersect([pricingInput,t.Object({id:uuid,cityId:uuid,version:t.Integer({minimum:1}),status:t.Union([t.Literal("DRAFT"),t.Literal("ACTIVE"),t.Literal("INACTIVE")]),createdByAccountId:uuid,createdAt:t.String({format:"date-time"}),activatedAt:t.Nullable(t.String({format:"date-time"})),deactivatedAt:t.Nullable(t.String({format:"date-time"}))})]);
const params=t.Object({cityId:uuid,versionId:uuid});
const errors={...standardErrors,400:errorResponse,403:errorResponse,404:errorResponse,409:errorResponse,422:errorResponse,503:errorResponse};
const cityHeader={name:"X-City-Id",in:"header",required:true,schema:{type:"string",format:"uuid"}} as const;
const estimateResponse=t.Object({cityId:uuid,store:t.Object({id:uuid,name:t.String(),orderAcceptanceStatus:t.Union([t.Literal("ACCEPTING"),t.Literal("PAUSED")])}),pricingVersion:t.Object({id:uuid,version:t.Integer({minimum:1})}),currency:t.Literal("IQD"),deliveryAvailable:t.Boolean(),reason:t.Nullable(t.Literal("ADDRESS_OUTSIDE_DELIVERY_ZONE")),deliveryFee:t.Nullable(t.Integer({minimum:0})),distanceSource:t.Nullable(t.Union([t.Literal("ROUTE"),t.Literal("STRAIGHT_LINE_FALLBACK")])),straightLineDistanceMeters:t.Integer({minimum:0}),pricingDistanceMeters:t.Nullable(t.Number({minimum:0})),routeDistanceMeters:t.Nullable(t.Number({minimum:0})),routeDurationSeconds:t.Nullable(t.Number({minimum:0})),fallbackReason:t.Nullable(t.Union([t.Literal("NO_ROUTE"),t.Literal("PROVIDER_FAILURE")])),billableDistanceMeters:t.Nullable(t.Number({minimum:0}))},{additionalProperties:false});

export const deliveryPricingRoutes=(auth:AuthModule,service:DeliveryPricingService)=>new Elysia({name:"delivery-pricing-routes"})
  .post("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions",async({request,set,params,body})=>service.create(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,body),{params:t.Object({cityId:uuid}),body:pricingInput,response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Create immutable DRAFT pricing version",security:[{bearerAuth:[]}]}})
  .post("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions/:versionId/activate",async({request,set,params})=>service.activate(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,params.versionId),{params,response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Atomically activate pricing version",description:"SUPER_ADMIN only. INACTIVE versions cannot be reactivated.",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions",async({request,set,params})=>service.list(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId),{params:t.Object({cityId:uuid}),response:{200:t.Array(pricing),...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"List City pricing history",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions/:versionId",async({request,set,params})=>service.getSuper(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,params.versionId),{params,response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Get pricing version",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId/delivery-pricing/active",async({request,set,params})=>service.activeForSuper(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId),{params:t.Object({cityId:uuid}),response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Get active City pricing",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/delivery-pricing/active",async({request,set})=>service.activeForAdmin(await authIdentity(auth,request,dashboardContext,requestIdOf(set))),{response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Get active pricing for signed ADMIN City",security:[{bearerAuth:[]}]}})
  .post("/api/v1/mobile/customer/delivery-pricing/estimate",async({request,set,body})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.estimate(identity.accountId,city.id,body);},{body:t.Object({storeId:uuid,addressId:t.Optional(uuid),destination:t.Optional(t.Object({latitude:t.Number({minimum:-90,maximum:90}),longitude:t.Number({minimum:-180,maximum:180})},{additionalProperties:false}))},{additionalProperties:false}),response:{200:estimateResponse,...errors},detail:{tags:["Customer — Delivery Estimate"],summary:"Estimate versioned delivery price",description:"Requires exactly one owned addressId or destination. PAUSED public Stores remain estimable. An address outside an ACTIVE Store delivery Zone returns deliveryAvailable=false without routing fallback. ROUTE uses OSRM meters unchanged; STRAIGHT_LINE_FALLBACK uses ceil(PostGIS ST_DistanceSphere) plus configured extra meters. Errors include ACTIVE_DELIVERY_PRICING_NOT_FOUND, ROUTE_NOT_FOUND, ROUTING_UNAVAILABLE, and MAX_DISTANCE_EXCEEDED.",security:[{bearerAuth:[]}],parameters:[cityHeader]}});
