import { Elysia, t } from "elysia";
import type { AuthModule } from "../auth/auth-module";
import { requirePublicCityContext } from "../auth/city/public-city-context";
import { customerContext, dashboardContext } from "../auth/core/context";
import { errorResponse, standardErrors } from "../auth/http/shared";
import { authIdentity, requestIdOf } from "../geography/shared";
import type { DeliveryPricingService } from "./delivery-pricing.service";

const uuid=t.String({format:"uuid"});
const pricingInput=t.Object({baseFee:t.Integer({minimum:0}),includedDistanceMeters:t.Integer({minimum:0}),pricePerKm:t.Integer({minimum:0}),roundingStep:t.Integer({minimum:1}),maximumDeliveryDistanceMeters:t.Nullable(t.Integer({minimum:1})),routingFallbackEnabled:t.Boolean(),fallbackOnNoRoute:t.Boolean(),fallbackOnProviderFailure:t.Boolean(),fallbackExtraDistanceMeters:t.Integer({minimum:0})},{additionalProperties:false});
const pricing=t.Object({...pricingInput.properties,id:uuid,cityId:uuid,version:t.Integer({minimum:1}),status:t.Union([t.Literal("DRAFT"),t.Literal("ACTIVE"),t.Literal("INACTIVE")]),createdByAccountId:uuid,createdAt:t.String({format:"date-time"}),activatedAt:t.Nullable(t.String({format:"date-time"})),deactivatedAt:t.Nullable(t.String({format:"date-time"})),activationRevision:t.Nullable(t.Integer({minimum:1}))},{additionalProperties:false});
const activePricing=t.Object({...pricingInput.properties,cityId:uuid,pricingVersionId:uuid,versionNumber:t.Integer({minimum:1}),activationRevision:t.Integer({minimum:1}),status:t.Literal("ACTIVE"),activatedAt:t.String({format:"date-time"}),routingProvider:t.Literal("OSRM"),routingTimeoutMs:t.Integer({minimum:1}),routingMaxAttempts:t.Literal(2),currency:t.Literal("IQD")},{additionalProperties:false});
const params=t.Object({cityId:uuid,versionId:uuid});
const errors={...standardErrors,400:errorResponse,403:errorResponse,404:errorResponse,409:errorResponse,422:errorResponse,499:errorResponse,502:errorResponse,503:errorResponse};
const cityHeader={name:"X-City-Id",in:"header",required:true,schema:{type:"string",format:"uuid"}} as const;
const estimateResponse=t.Object({store:t.Object({id:uuid,name:t.String(),orderAcceptanceStatus:t.Union([t.Literal("ACCEPTING"),t.Literal("PAUSED")])}),currency:t.Literal("IQD"),deliveryAvailable:t.Boolean(),reason:t.Nullable(t.Union([t.Literal("ADDRESS_OUTSIDE_DELIVERY_ZONE"),t.Literal("ROUTE_NOT_FOUND"),t.Literal("MAX_DISTANCE_EXCEEDED")])),deliveryFee:t.Nullable(t.Integer({minimum:0})),retryable:t.Boolean(),distanceSource:t.Nullable(t.Union([t.Literal("ROUTE"),t.Literal("STRAIGHT_LINE_FALLBACK")])),distanceMeters:t.Nullable(t.Number({minimum:0})),durationSeconds:t.Nullable(t.Number({minimum:0})),routingProvider:t.String(),pricingVersionId:uuid,pricingVersionNumber:t.Integer({minimum:1}),fallbackReason:t.Nullable(t.Union([t.Literal("NO_ROUTE"),t.Literal("PROVIDER_FAILURE")])),fallbackExtraDistanceMeters:t.Nullable(t.Integer({minimum:0}))},{additionalProperties:false});

export const deliveryPricingRoutes=(auth:AuthModule,service:DeliveryPricingService)=>new Elysia({name:"delivery-pricing-routes"})
  .post("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions",async({request,set,params,body})=>service.create(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,body,requestIdOf(set)),{params:t.Object({cityId:uuid}),body:pricingInput,response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Create immutable DRAFT pricing version",security:[{bearerAuth:[]}]}})
  .post("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions/:versionId/activate",async({request,set,params})=>service.activate(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,params.versionId,requestIdOf(set)),{params,response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Atomically activate pricing version",description:"SUPER_ADMIN only. INACTIVE versions cannot be reactivated. Redis is updated after commit using activation-revision CAS.",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions",async({request,set,params})=>service.list(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId),{params:t.Object({cityId:uuid}),response:{200:t.Array(pricing),...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"List City pricing history",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId/delivery-pricing/versions/:versionId",async({request,set,params})=>service.getSuper(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,params.versionId),{params,response:{200:pricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Get pricing version",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId/delivery-pricing/active",async({request,set,params})=>service.activeForSuper(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId),{params:t.Object({cityId:uuid}),response:{200:activePricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Get active City pricing",security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/delivery-pricing/active",async({request,set})=>service.activeForAdmin(await authIdentity(auth,request,dashboardContext,requestIdOf(set))),{response:{200:activePricing,...errors},detail:{tags:["Dashboard — Delivery Pricing"],summary:"Get active pricing for signed ADMIN City",security:[{bearerAuth:[]}]}})
  .post("/api/v1/mobile/customer/delivery-pricing/estimate",async({request,set,body})=>{const requestId=requestIdOf(set);const identity=await authIdentity(auth,request,customerContext,requestId);const {city}=await requirePublicCityContext(auth.client,request);return service.estimatePublic(identity.accountId,city.id,{...body,requestId,signal:request.signal});},{body:t.Object({storeId:uuid,addressId:t.Optional(uuid),destination:t.Optional(t.Object({latitude:t.Number({minimum:-90,maximum:90}),longitude:t.Number({minimum:-180,maximum:180})},{additionalProperties:false}))},{additionalProperties:false}),response:{200:estimateResponse,...errors},detail:{tags:["Customer — Delivery Estimate"],summary:"Estimate versioned delivery price",description:"Domain unavailability (outside Zone, NoRoute without fallback, maximum distance) returns HTTP 200 with a reason and null fee. Transient exhausted routing failures return sanitized ROUTING_UNAVAILABLE (503). Internal snapshots are not exposed.",security:[{bearerAuth:[]}],parameters:[cityHeader]}});
