import { SAMPLE } from "../samples";

export const orderExamples = {
  create: {
    storeId: SAMPLE.storeId,
    addressId: SAMPLE.addressId,
    paymentMethod: "CASH",
    items: [
      {
        productId: SAMPLE.productId,
        sizeId: SAMPLE.sizeId,
        quantity: 1,
        modifierSelections: [
          { modifierOptionId: SAMPLE.modifierOptionId, quantity: 1 },
        ],
      },
    ],
    idempotencyKey: SAMPLE.idempotencyKey,
  },
  cancel: { reason: "Customer requested cancellation" },
  replaceItem: {
    productId: SAMPLE.productId,
    sizeId: SAMPLE.sizeId,
    quantity: 1,
    modifierSelections: [
      { modifierOptionId: SAMPLE.modifierOptionId, quantity: 1 },
    ],
    reason: "Item unavailable",
    customerAgreedByPhone: true,
  },
  quantity: { quantity: 2, reason: "Customer agreed quantity change" },
  addItem: {
    productId: SAMPLE.productId,
    sizeId: SAMPLE.sizeId,
    quantity: 1,
    reason: "Customer added an item by phone",
  },
  estimateSavedAddress: { storeId: SAMPLE.storeId, addressId: SAMPLE.addressId },
  estimateDirect: {
    storeId: SAMPLE.storeId,
    destination: {
      latitude: SAMPLE.baghdadLat,
      longitude: SAMPLE.baghdadLng,
    },
  },
  deliveryPricingCreate: {
    baseFee: 2000,
    includedDistanceMeters: 1000,
    pricePerKm: 500,
    roundingStep: 250,
    maximumDeliveryDistanceMeters: 15000,
    routingFallbackEnabled: true,
    fallbackOnNoRoute: true,
    fallbackOnProviderFailure: true,
    fallbackExtraDistanceMeters: 100,
  },
  driverPricing: {
    pricingBase: 2000,
    roundingUnit: 250,
    pricingStages: [{ afterSeconds: 60, increasePercentage: 10 }],
  },
  offerStop: { reason: "No available drivers" },
  assignDriver: { driverId: SAMPLE.driverId },
  proofUploadIntent: {
    assignmentId: SAMPLE.assignmentId,
    purpose: "PICKUP_PROOF",
    contentType: "image/jpeg",
    fileName: "pickup.jpg",
    sizeBytes: 180_000,
  },
  driverDelivery: {
    proofFileId: SAMPLE.mediaAssetId,
    collectedAmount: 12500,
    note: "Collected in cash",
  },
  dashboardDelivery: {
    collectedAmount: 12500,
    reason: "Dashboard completed collection",
    note: "Customer paid cash",
    actedOnBehalfOf: "DRIVER",
  },
  empty: {},
  arrival: { note: "Arrived at store" },
  override: { reason: "Dashboard override" },
  pickup: { proofFileId: SAMPLE.mediaAssetId, note: "Picked up" },
  handoff: { reason: "Handoff to another driver" },
  dashboardOps: {
    orderId: SAMPLE.orderId,
    orderNumber: "PP-1001",
    status: "PICKED_UP",
    custodyStatus: "WITH_DRIVER",
    custodyDriverId: SAMPLE.driverId,
    driverAccountId: SAMPLE.driverId,
    lockedDriverFee: 2000,
    storeReadyMarkedAt: SAMPLE.instant,
    version: 4,
    statusChangedAt: SAMPLE.instant,
    cancelledAt: null,
    assignments: [
      {
        id: SAMPLE.assignmentId,
        driverId: SAMPLE.driverId,
        status: "PICKED_UP",
        assignmentSource: "OFFER_CLAIM",
        assignmentSequence: 1,
        assignmentReason: null,
        driverFee: 2000,
        offerRoundId: SAMPLE.offerId,
        assignedAt: SAMPLE.instant,
        arrivedAtStoreAt: SAMPLE.instant,
        pickedUpAt: SAMPLE.instant,
        arrivedAtCustomerAt: null,
        completedAt: null,
        cancelledAt: null,
      },
    ],
    handoff: null,
    returnWorkflow: null,
    openOfferRound: null,
  },
  commission: {
    platformCommissionRate: 15,
    reason: "Seasonal adjustment",
    note: "Reviewed with finance",
  },
};
