import { Elysia, t } from "elysia";
import type { AuthModule } from "../auth/auth-module";
import { customerContext, dashboardContext, driverContext, type AuthenticationContext } from "../auth/core/context";
import { bearer, errorResponse, parseAuthenticationBody, requestIdOf, standardErrors } from "../auth/http/shared";
import { GeographyService } from "./service";

const pageQuery={page:t.Optional(t.Numeric({minimum:1})),limit:t.Optional(t.Numeric({minimum:1,maximum:100})),search:t.Optional(t.String({maxLength:100})),status:t.Optional(t.String({maxLength:20}))};
const date=t.String({format:"date-time"});
const govSummary=t.Object({id:t.String({format:"uuid"}),nameAr:t.String(),nameEn:t.String(),status:t.Union([t.Literal("ACTIVE"),t.Literal("INACTIVE")])});
const govDto=t.Object({id:t.String({format:"uuid"}),nameAr:t.String(),nameEn:t.String(),status:t.Union([t.Literal("ACTIVE"),t.Literal("INACTIVE")]),displayOrder:t.Integer(),createdAt:date,updatedAt:date});
const cityDto=t.Object({id:t.String({format:"uuid"}),governorateId:t.String({format:"uuid"}),nameAr:t.String(),nameEn:t.String(),latitude:t.Number(),longitude:t.Number(),status:t.Union([t.Literal("DRAFT"),t.Literal("ACTIVE"),t.Literal("SUSPENDED"),t.Literal("ARCHIVED")]),displayOrder:t.Integer(),createdAt:date,updatedAt:date,archivedAt:t.Nullable(date),governorate:govSummary});
const mobileGov=t.Object({id:t.String({format:"uuid"}),nameAr:t.String(),nameEn:t.String()});
const mobileCity=t.Object({id:t.String({format:"uuid"}),nameAr:t.String(),nameEn:t.String(),latitude:t.Number(),longitude:t.Number(),displayOrder:t.Integer(),governorate:mobileGov});
const paginated=(item:any)=>t.Object({data:t.Array(item),page:t.Number(),limit:t.Number(),total:t.Number()});
const govResponse=paginated(govDto), cityResponse=paginated(cityDto), mobileCityResponse=paginated(mobileCity);
const errors=(extra:Record<number,any>={})=>({...standardErrors,400:errorResponse,403:errorResponse,404:errorResponse,409:errorResponse,...extra});
const idParam=t.Object({governorateId:t.String({format:"uuid"})},{additionalProperties:false});
const cityIdParam=t.Object({cityId:t.String({format:"uuid"})},{additionalProperties:false});
const authIdentity=(auth:AuthModule,request:Request,context:AuthenticationContext,requestId:string)=>auth.sessions.authenticate(bearer(request),context,requestId);

export const geographyRoutes=(auth:AuthModule,service:GeographyService)=>new Elysia({name:"geography-routes"})
  .onParse(parseAuthenticationBody)
  .get("/api/v1/dashboard/governorates",async({request,set,query})=>{await authIdentity(auth,request,dashboardContext,requestIdOf(set));return service.governorates(query);},{query:t.Object({...pageQuery,status:t.Optional(t.Union([t.Literal("ACTIVE"),t.Literal("INACTIVE")]))},{additionalProperties:false}),response:{200:govResponse,...errors()},detail:{tags:["Dashboard — Governorates"],security:[{bearerAuth:[]}]}})
  .patch("/api/v1/dashboard/governorates/:governorateId",async({request,set,params,body})=>{const id=await authIdentity(auth,request,dashboardContext,requestIdOf(set));return service.updateGovernorate(id,params.governorateId,body);},{params:idParam,body:t.Object({status:t.Optional(t.Union([t.Literal("ACTIVE"),t.Literal("INACTIVE")])),displayOrder:t.Optional(t.Integer({minimum:0}))},{additionalProperties:false,minProperties:1}),response:{200:govDto,...errors()},detail:{tags:["Dashboard — Governorates"],security:[{bearerAuth:[]}]}})
  .post("/api/v1/dashboard/cities",async({request,set,body})=>service.createCity(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),body),{body:t.Object({governorateId:t.String({format:"uuid"}),nameAr:t.String({minLength:1,maxLength:200}),nameEn:t.String({minLength:1,maxLength:200}),latitude:t.Number({minimum:-90,maximum:90}),longitude:t.Number({minimum:-180,maximum:180}),displayOrder:t.Integer({minimum:0})},{additionalProperties:false}),response:{200:cityDto,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities",async({request,set,query})=>{await authIdentity(auth,request,dashboardContext,requestIdOf(set));return service.cities(query);},{query:t.Object({governorateId:t.Optional(t.String({format:"uuid"})),...pageQuery,status:t.Optional(t.Union([t.Literal("DRAFT"),t.Literal("ACTIVE"),t.Literal("SUSPENDED"),t.Literal("ARCHIVED")]))},{additionalProperties:false}),response:{200:cityResponse,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .get("/api/v1/dashboard/cities/:cityId",async({request,set,params})=>{await authIdentity(auth,request,dashboardContext,requestIdOf(set));return service.city(params.cityId);},{params:cityIdParam,response:{200:cityDto,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .patch("/api/v1/dashboard/cities/:cityId",async({request,set,params,body})=>service.updateCity(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,body),{params:cityIdParam,body:t.Object({governorateId:t.Optional(t.String({format:"uuid"})),nameAr:t.Optional(t.String({minLength:1,maxLength:200})),nameEn:t.Optional(t.String({minLength:1,maxLength:200})),latitude:t.Optional(t.Number({minimum:-90,maximum:90})),longitude:t.Optional(t.Number({minimum:-180,maximum:180})),displayOrder:t.Optional(t.Integer({minimum:0}))},{additionalProperties:false,minProperties:1}),response:{200:cityDto,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .post("/api/v1/dashboard/cities/:cityId/activate",async({request,set,params})=>service.transition(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,"ACTIVE"),{params:cityIdParam,response:{200:cityDto,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .post("/api/v1/dashboard/cities/:cityId/suspend",async({request,set,params})=>service.transition(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,"SUSPENDED"),{params:cityIdParam,response:{200:cityDto,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .post("/api/v1/dashboard/cities/:cityId/archive",async({request,set,params})=>service.transition(await authIdentity(auth,request,dashboardContext,requestIdOf(set)),params.cityId,"ARCHIVED"),{params:cityIdParam,response:{200:cityDto,...errors()},detail:{tags:["Dashboard — Cities"],security:[{bearerAuth:[]}]}})
  .get("/api/v1/mobile/customer/cities",async({request,set,query})=>{await authIdentity(auth,request,customerContext,requestIdOf(set));return service.cities({...query,mobile:true});},{query:t.Object({page:t.Optional(t.Numeric({minimum:1})),limit:t.Optional(t.Numeric({minimum:1,maximum:100})),search:t.Optional(t.String({maxLength:100}))},{additionalProperties:false}),response:{200:mobileCityResponse,...errors()},detail:{tags:["Mobile — Customer Cities"],security:[{bearerAuth:[]}]}})
  .get("/api/v1/mobile/driver/cities",async({request,set,query})=>{await authIdentity(auth,request,driverContext,requestIdOf(set));return service.cities({...query,mobile:true});},{query:t.Object({page:t.Optional(t.Numeric({minimum:1})),limit:t.Optional(t.Numeric({minimum:1,maximum:100})),search:t.Optional(t.String({maxLength:100}))},{additionalProperties:false}),response:{200:mobileCityResponse,...errors()},detail:{tags:["Mobile — Driver Cities"],security:[{bearerAuth:[]}]}});
