import { Elysia, t } from "elysia";
import type { AuthModule } from "../auth/auth-module";
import { requirePublicCityContext } from "../auth/city/public-city-context";
import { customerContext } from "../auth/core/context";
import { errorResponse, standardErrors } from "../auth/http/shared";
import { authIdentity, requestIdOf } from "../geography/shared";
import type { CartService } from "./cart.service";

const selection=t.Object({modifierOptionId:t.String({format:"uuid"}),quantity:t.Optional(t.Integer({minimum:1,maximum:99}))},{additionalProperties:false});
const sizeId=t.Union([t.String({format:"uuid"}),t.Null()]);
const itemBody=t.Object({storeId:t.String({format:"uuid"}),productId:t.String({format:"uuid"}),sizeId:t.Optional(sizeId),quantity:t.Integer({minimum:1,maximum:99}),modifierSelections:t.Optional(t.Array(selection))},{additionalProperties:false});
const cartResponse=t.Object({
  id:t.String({format:"uuid"}),status:t.Literal("ACTIVE"),cityId:t.String({format:"uuid"}),
  store:t.Object({id:t.String({format:"uuid"}),name:t.String(),orderAcceptanceStatus:t.Union([t.Literal("ACCEPTING"),t.Literal("PAUSED")])}),
  items:t.Array(t.Object({id:t.String({format:"uuid"}),product:t.Object({id:t.String({format:"uuid"}),name:t.String()}),selectedSize:t.Nullable(t.Object({id:t.String({format:"uuid"}),name:t.String(),currentPrice:t.Integer({exclusiveMinimum:0}),isAvailable:t.Boolean(),isValid:t.Boolean()})),quantity:t.Integer({minimum:1,maximum:99}),modifierSelections:t.Array(t.Object({modifierOptionId:t.String({format:"uuid"}),name:t.String(),quantity:t.Integer({minimum:1}),currentUnitPrice:t.Integer({minimum:0}),isValid:t.Boolean()})),currentUnitPrice:t.Integer({exclusiveMinimum:0}),currentModifiersPrice:t.Integer({minimum:0}),currentLineTotal:t.Integer({exclusiveMinimum:0}),priceChanged:t.Boolean(),isAvailable:t.Boolean(),isValid:t.Boolean(),isOrderable:t.Boolean(),validationReasons:t.Array(t.String())})),
  itemsSubtotal:t.Integer({minimum:0}),priceChanged:t.Boolean(),isOrderable:t.Boolean(),createdAt:t.String({format:"date-time"}),updatedAt:t.String({format:"date-time"}),
});
const errors={...standardErrors,400:errorResponse,404:errorResponse,409:errorResponse,422:errorResponse};
const cityParameter={name:"X-City-Id",in:"header",required:true,schema:{type:"string",format:"uuid"}} as const;

export const cartRoutes=(auth:AuthModule,service:CartService)=>new Elysia({name:"customer-cart-routes"})
  .get("/api/v1/mobile/customer/cart",async({request,set})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.get(identity.accountId,city.id)},{response:{200:cartResponse,...errors},detail:{tags:["Customer — Cart"],summary:"Get active Cart",description:"Customer-authenticated persistent active Cart. Current Catalog prices and validation state are authoritative. Returns CART_NOT_FOUND when no Cart has ever been created.",security:[{bearerAuth:[]}],parameters:[cityParameter]}})
  .post("/api/v1/mobile/customer/cart/items",async({request,set,body})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.add(identity.accountId,city.id,body.storeId,body)},{body:itemBody,response:{200:cartResponse,...errors},detail:{tags:["Customer — Cart"],summary:"Add Cart Item",description:"Adds or atomically increments the same Product + selected Size + effective Modifier configuration. Size-priced Products require a selectable sizeId; base-priced Products do not accept one. Current Catalog prices are authoritative. A different Store/City returns CART_STORE_CONFLICT/CART_CITY_CONFLICT; PAUSED Stores reject mutations.",security:[{bearerAuth:[]}],parameters:[cityParameter]}})
  .patch("/api/v1/mobile/customer/cart/items/:itemId",async({request,set,params,body})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.update(identity.accountId,city.id,params.itemId,body)},{params:t.Object({itemId:t.String({format:"uuid"})}),body:t.Object({quantity:t.Integer({minimum:1,maximum:99}),sizeId:t.Optional(sizeId),modifierSelections:t.Optional(t.Array(selection))},{additionalProperties:false}),response:{200:cartResponse,...errors},detail:{tags:["Customer — Cart"],summary:"Update Cart Item",description:"Updates quantity and optionally replaces the selected Size/Modifier configuration atomically. A changed configuration merges with an existing identical logical Item. Quantity must be 1–99; zero is never an implicit delete. PAUSED Stores reject mutations.",security:[{bearerAuth:[]}],parameters:[cityParameter]}})
  .delete("/api/v1/mobile/customer/cart/items/:itemId",async({request,set,params})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.remove(identity.accountId,city.id,params.itemId)},{params:t.Object({itemId:t.String({format:"uuid"})}),response:{200:cartResponse,...errors},detail:{tags:["Customer — Cart"],summary:"Delete Cart Item",description:"Deletes the Item but preserves the active Cart even when it becomes empty.",security:[{bearerAuth:[]}],parameters:[cityParameter]}})
  .delete("/api/v1/mobile/customer/cart/items",async({request,set})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.clear(identity.accountId,city.id)},{response:{200:cartResponse,...errors},detail:{tags:["Customer — Cart"],summary:"Clear Cart",description:"Removes all Items while preserving the active Cart. PAUSED Stores reject mutations.",security:[{bearerAuth:[]}],parameters:[cityParameter]}})
  .put("/api/v1/mobile/customer/cart",async({request,set,body})=>{const identity=await authIdentity(auth,request,customerContext,requestIdOf(set));const {city}=await requirePublicCityContext(auth.client,request);return service.replace(identity.accountId,city.id,body.storeId,body)},{body:itemBody,response:{200:cartResponse,...errors},detail:{tags:["Customer — Cart"],summary:"Atomically replace Cart",description:"Validates the target Product, selected Size, and effective Modifiers before atomically replacing the prior Cart contents and Store/City scope. Failure preserves the prior Cart.",security:[{bearerAuth:[]}],parameters:[cityParameter]}});
