import { describe,expect,test } from "bun:test";
import { FakeActivePricingCache,parseActivePricing,type ActivePricing } from "../../src/modules/delivery-pricing/active-pricing-cache";
import { OsrmRoutingProvider } from "../../src/modules/delivery-pricing/osrm-routing-provider";
import { RoutingError } from "../../src/modules/delivery-pricing/routing-provider";
import type { Logger,LogRecord } from "../../src/observability/logger";
import type { SQL } from "bun";
import { DeliveryPricingService } from "../../src/modules/delivery-pricing/delivery-pricing.service";
import { FakeRoutingProvider } from "../../src/modules/delivery-pricing/routing-provider";
import type { AuthIdentity } from "../../src/modules/auth/sessions/session-service";

const active:ActivePricing={cityId:"11111111-1111-4111-8111-111111111111",pricingVersionId:"22222222-2222-4222-8222-222222222222",versionNumber:1,activationRevision:10,status:"ACTIVE",activatedAt:new Date().toISOString(),routingProvider:"OSRM",routingTimeoutMs:1000,routingMaxAttempts:2,baseFee:1000,includedDistanceMeters:0,pricePerKm:500,roundingStep:250,maximumDeliveryDistanceMeters:null,routingFallbackEnabled:true,fallbackOnNoRoute:true,fallbackOnProviderFailure:true,fallbackExtraDistanceMeters:100,currency:"IQD"};
const context={requestId:"request-1",cityId:active.cityId,storeId:"store",pricingVersionId:active.pricingVersionId};
const points={latitude:33.3,longitude:44.4};
const logger=()=>{const records:LogRecord[]=[];const write=(r:LogRecord)=>records.push(r);return {records,value:{debug:write,info:write,warn:write,error:write} as Logger};};

describe("active pricing cache",()=>{
  test("validates City, lifecycle and complete schema",()=>{expect(parseActivePricing(JSON.stringify(active),active.cityId)).toEqual(active);expect(parseActivePricing(JSON.stringify({...active,cityId:"other"}),active.cityId)).toBeNull();expect(parseActivePricing("{bad",active.cityId)).toBeNull();expect(parseActivePricing(JSON.stringify({...active,status:"DRAFT"}),active.cityId)).toBeNull();});
  test("atomic newer revision cannot be overwritten by stale reader",async()=>{const cache=new FakeActivePricingCache();await cache.writeIfNewer(active.cityId,{...active,activationRevision:11},100);expect(await cache.writeIfNewer(active.cityId,active,100)).toBeFalse();expect(JSON.parse((await cache.get(active.cityId))!).activationRevision).toBe(11);});
  test("cached payload contains no Customer data or secrets",()=>{const raw=JSON.stringify(active);for(const forbidden of ["customer","address","authorization","apiKey","password","url"])expect(raw.toLowerCase()).not.toContain(forbidden.toLowerCase());});
  test("cache hit reads only authoritative revision, not full pricing",async()=>{const cache=new FakeActivePricingCache();cache.values.set(active.cityId,JSON.stringify(active));let dbReads=0;const database={unsafe:async(query:string)=>{dbReads++;expect(query).toContain("select activation_revision");expect(query).not.toContain("base_fee");return [{activationRevision:active.activationRevision}];}} as unknown as SQL;const service=new DeliveryPricingService(database,new FakeRoutingProvider({distanceMeters:1,durationSeconds:1}),logger().value,cache,{cacheTtlSeconds:21600,routingTimeoutMs:1000,routingProvider:"OSRM"});const identity={accountId:"a",sessionId:"s",applicationType:"DASHBOARD",roles:["SUPER_ADMIN"],scopeType:"GLOBAL",cityId:null,storeId:null} as AuthIdentity;expect((await service.activeForSuper(identity,active.cityId)).pricingVersionId).toBe(active.pricingVersionId);expect(dbReads).toBe(1);});
  test("cache miss reads DB once and fills Redis",async()=>{const cache=new FakeActivePricingCache();let dbReads=0;const row={id:active.pricingVersionId,cityId:active.cityId,version:1,status:"ACTIVE",baseFee:1000,includedDistanceMeters:0,pricePerKm:500,roundingStep:250,maximumDeliveryDistanceMeters:null,routingFallbackEnabled:true,fallbackOnNoRoute:true,fallbackOnProviderFailure:true,fallbackExtraDistanceMeters:100,createdByAccountId:"a",createdAt:new Date(),activatedAt:new Date(active.activatedAt),deactivatedAt:null,activationRevision:10};const database={unsafe:async()=>{dbReads++;return [row];}} as unknown as SQL;const service=new DeliveryPricingService(database,new FakeRoutingProvider({distanceMeters:1,durationSeconds:1}),logger().value,cache,{cacheTtlSeconds:21600,routingTimeoutMs:1000,routingProvider:"OSRM"});const identity={accountId:"a",sessionId:"s",applicationType:"DASHBOARD",roles:["SUPER_ADMIN"],scopeType:"GLOBAL",cityId:null,storeId:null} as AuthIdentity;await Promise.all([service.activeForSuper(identity,active.cityId),service.activeForSuper(identity,active.cityId)]);expect(dbReads).toBe(1);expect(cache.writes).toBe(1);});
  test("stale revision bypasses cache and loads the full active version",async()=>{const cache=new FakeActivePricingCache();cache.values.set(active.cityId,JSON.stringify(active));const current={...active,pricingVersionId:"33333333-3333-4333-8333-333333333333",activationRevision:11};let calls=0;const row={id:current.pricingVersionId,cityId:current.cityId,version:2,status:"ACTIVE",baseFee:2000,includedDistanceMeters:0,pricePerKm:500,roundingStep:250,maximumDeliveryDistanceMeters:null,routingFallbackEnabled:true,fallbackOnNoRoute:true,fallbackOnProviderFailure:true,fallbackExtraDistanceMeters:100,createdByAccountId:"a",createdAt:new Date(),activatedAt:new Date(current.activatedAt),deactivatedAt:null,activationRevision:11};const database={unsafe:async(query:string)=>{calls++;return query.includes("select activation_revision")?[{activationRevision:11}]:[row];}} as unknown as SQL;const service=new DeliveryPricingService(database,new FakeRoutingProvider({distanceMeters:1,durationSeconds:1}),logger().value,cache,{cacheTtlSeconds:21600,routingTimeoutMs:1000,routingProvider:"OSRM"});const identity={accountId:"a",sessionId:"s",applicationType:"DASHBOARD",roles:["SUPER_ADMIN"],scopeType:"GLOBAL",cityId:null,storeId:null} as AuthIdentity;expect((await service.activeForSuper(identity,active.cityId)).pricingVersionId).toBe(current.pricingVersionId);expect(calls).toBe(2);});
  test("single-flight entry is removed after a failed load",async()=>{const cache=new FakeActivePricingCache();let calls=0;const row={id:active.pricingVersionId,cityId:active.cityId,version:1,status:"ACTIVE",baseFee:1000,includedDistanceMeters:0,pricePerKm:500,roundingStep:250,maximumDeliveryDistanceMeters:null,routingFallbackEnabled:true,fallbackOnNoRoute:true,fallbackOnProviderFailure:true,fallbackExtraDistanceMeters:100,createdByAccountId:"a",createdAt:new Date(),activatedAt:new Date(active.activatedAt),deactivatedAt:null,activationRevision:10};const database={unsafe:async()=>{calls++;return calls===1?[]:[row];}} as unknown as SQL;const service=new DeliveryPricingService(database,new FakeRoutingProvider({distanceMeters:1,durationSeconds:1}),logger().value,cache,{cacheTtlSeconds:21600,routingTimeoutMs:1000,routingProvider:"OSRM"});const identity={accountId:"a",sessionId:"s",applicationType:"DASHBOARD",roles:["SUPER_ADMIN"],scopeType:"GLOBAL",cityId:null,storeId:null} as AuthIdentity;await expect(service.activeForSuper(identity,active.cityId)).rejects.toMatchObject({publicCode:"ACTIVE_DELIVERY_PRICING_NOT_FOUND"});expect((await service.activeForSuper(identity,active.cityId)).pricingVersionId).toBe(active.pricingVersionId);expect(calls).toBe(2);});
});

describe("OSRM retry and typed classification",()=>{
  test("temporary HTTP retries once then succeeds and logs each attempt",async()=>{let calls=0;const log=logger();const provider=new OsrmRoutingProvider("https://routing.example","driving",100,log.value,async()=>++calls===1?new Response("",{status:503}):Response.json({code:"Ok",routes:[{distance:4275,duration:620}]}),async()=>{});const result=await provider.route(points,{latitude:33.4,longitude:44.5},context);expect(result).toMatchObject({distanceMeters:4275,attempts:2});expect(calls).toBe(2);expect(log.records.filter(x=>x.event==="routing_attempt")).toHaveLength(2);expect(JSON.stringify(log.records)).not.toContain("route/v1");});
  test("NoRoute is typed and never retried",async()=>{let calls=0;const log=logger();const provider=new OsrmRoutingProvider("https://routing.example","driving",100,log.value,async()=>{calls++;return Response.json({code:"NoRoute",routes:[]});},async()=>{});await expect(provider.route(points,points,context)).rejects.toMatchObject({details:{classification:"NO_ROUTE",retryable:false}});expect(calls).toBe(1);});
  test("invalid JSON and permanent HTTP are non-retryable",async()=>{for(const [response,classification] of [[new Response("bad"),"INVALID_JSON"],[new Response("",{status:401}),"PERMANENT_HTTP_ERROR"]] as const){let calls=0;const provider=new OsrmRoutingProvider("https://routing.example","driving",100,logger().value,async()=>{calls++;return response;},async()=>{});await expect(provider.route(points,points,context)).rejects.toMatchObject({details:{classification}});expect(calls).toBe(1);}});
  test("timeout retries exactly once and remains retryable",async()=>{let calls=0;const provider=new OsrmRoutingProvider("https://routing.example","driving",5,logger().value,async(_url,init)=>{calls++;return new Promise((_resolve,reject)=>init!.signal!.addEventListener("abort",()=>reject(new DOMException("timeout","AbortError")),{once:true}));},async()=>{});try{await provider.route(points,points,context);throw new Error("expected");}catch(error){expect(error).toBeInstanceOf(RoutingError);expect((error as RoutingError).details).toMatchObject({classification:"TIMEOUT",attemptNumber:2,retryable:true});}expect(calls).toBe(2);});
  test("invalid coordinates fail before HTTP",async()=>{let calls=0;const provider=new OsrmRoutingProvider("https://routing.example","driving",100,logger().value,async()=>{calls++;return Response.json({});});await expect(provider.route({latitude:91,longitude:0},points,context)).rejects.toMatchObject({details:{classification:"INVALID_COORDINATES"}});expect(calls).toBe(0);});
  test("profile is strictly driving",()=>expect(()=>new OsrmRoutingProvider("https://routing.example","walking" as "driving",100,logger().value)).toThrow());
});
