/**
 * Source of truth for Dashboard LIST GET endpoints (24) and matching Excel exports.
 * Used by contract, OpenAPI, and list/export parity tests.
 */
export const DASHBOARD_LIST_SCOPE = {
  GLOBAL: "GLOBAL",
  CITY: "CITY",
  SUPER_ADMIN_EXPLICIT_CITY: "SUPER_ADMIN_EXPLICIT_CITY",
} as const;

export type DashboardListScope =
  (typeof DASHBOARD_LIST_SCOPE)[keyof typeof DASHBOARD_LIST_SCOPE];

export type DashboardListEndpoint = {
  id: string;
  method: "GET";
  pathTemplate: string;
  scope: DashboardListScope;
  /** Token used for the happy-path contract. */
  actor: "super" | "admin";
  readPermission: string | "SUPER_ADMIN" | "CITY_ADMIN";
  sortAllowlist: readonly string[];
  defaultSortBy: string;
  filters: readonly string[];
  unimplementedFilters: readonly string[];
  exportPathTemplate: string | null;
  idField: string;
  searchHit: string;
  andFilters: Record<string, string>;
  needsSeed: boolean;
};

export const DASHBOARD_LIST_ENDPOINTS: readonly DashboardListEndpoint[] = [
  {
    id: "governorates",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/governorates",
    scope: "GLOBAL",
    actor: "super",
    readPermission: "SUPER_ADMIN",
    sortAllowlist: ["displayOrder", "nameEn", "nameAr", "status", "createdAt"],
    defaultSortBy: "displayOrder",
    filters: ["status", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/governorates/export",
    idField: "id",
    searchHit: "Baghdad",
    andFilters: { status: "ACTIVE", search: "Baghdad" },
    needsSeed: false,
  },
  {
    id: "cities",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/cities",
    scope: "GLOBAL",
    actor: "super",
    readPermission: "SUPER_ADMIN",
    sortAllowlist: ["displayOrder", "nameEn", "nameAr", "status", "createdAt"],
    defaultSortBy: "displayOrder",
    filters: ["governorateId", "status", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/cities/export",
    idField: "id",
    searchHit: "ZXQ-CITY-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-CITY-HIT" },
    needsSeed: true,
  },
  {
    id: "zones",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/zones",
    scope: "SUPER_ADMIN_EXPLICIT_CITY",
    actor: "super",
    readPermission: "SUPER_ADMIN",
    sortAllowlist: ["name", "status", "createdAt"],
    defaultSortBy: "name",
    filters: ["cityId", "status", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/zones/export",
    idField: "id",
    searchHit: "ZXQ-ZONE-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-ZONE-HIT" },
    needsSeed: true,
  },
  {
    id: "stores",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/stores",
    scope: "CITY",
    actor: "admin",
    readPermission: "stores.read",
    sortAllowlist: ["displayOrder", "name", "status", "createdAt", "platformCommissionRate"],
    defaultSortBy: "displayOrder",
    filters: [
      "status",
      "mainCategoryId",
      "zoneId",
      "commissionRateMin",
      "commissionRateMax",
      "createdFrom",
      "createdTo",
    ],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/stores/export",
    idField: "id",
    searchHit: "ZXQ-STORE-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-STORE-HIT" },
    needsSeed: true,
  },
  {
    id: "store-commissions",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/store-commissions",
    scope: "CITY",
    actor: "admin",
    readPermission: "stores.commission.read",
    sortAllowlist: ["displayOrder", "name", "status", "createdAt", "platformCommissionRate"],
    defaultSortBy: "displayOrder",
    filters: [
      "status",
      "commissionRateMin",
      "commissionRateMax",
      "createdFrom",
      "createdTo",
    ],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/store-commissions/export",
    idField: "storeId",
    searchHit: "ZXQ-STORE-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-STORE-HIT" },
    needsSeed: true,
  },
  {
    id: "store-commission-history",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/store-commissions/:storeId/history",
    scope: "CITY",
    actor: "admin",
    readPermission: "stores.commission.read",
    sortAllowlist: ["changedAt", "newRate"],
    defaultSortBy: "changedAt",
    filters: [],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/store-commission-history/export",
    idField: "id",
    searchHit: "ZXQ-HIST-HIT",
    andFilters: { search: "ZXQ-HIST-HIT" },
    needsSeed: true,
  },
  {
    id: "main-categories",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/main-categories",
    scope: "CITY",
    actor: "admin",
    readPermission: "main_categories.read",
    sortAllowlist: ["displayOrder", "name", "createdAt"],
    defaultSortBy: "displayOrder",
    filters: ["status"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/main-categories/export",
    idField: "id",
    searchHit: "ZXQ-MAIN-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-MAIN-HIT" },
    needsSeed: true,
  },
  {
    id: "subcategories",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/subcategories",
    scope: "CITY",
    actor: "admin",
    readPermission: "subcategories.read",
    sortAllowlist: ["displayOrder", "name", "createdAt"],
    defaultSortBy: "displayOrder",
    filters: ["mainCategoryId", "status"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/subcategories/export",
    idField: "id",
    searchHit: "ZXQ-SUB-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-SUB-HIT" },
    needsSeed: true,
  },
  {
    id: "store-categories",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/stores/:storeId/categories",
    scope: "CITY",
    actor: "admin",
    readPermission: "store_categories.read",
    sortAllowlist: ["displayOrder", "name", "createdAt"],
    defaultSortBy: "displayOrder",
    filters: ["status", "parentCategoryId", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/stores/:storeId/categories/export",
    idField: "id",
    searchHit: "ZXQ-SCAT-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-SCAT-HIT" },
    needsSeed: true,
  },
  {
    id: "products",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/stores/:storeId/products",
    scope: "CITY",
    actor: "admin",
    readPermission: "products.read",
    sortAllowlist: ["displayOrder", "name", "createdAt"],
    defaultSortBy: "displayOrder",
    filters: [
      "status",
      "categoryId",
      "isAvailable",
      "hasSizes",
      "modifierGroupId",
      "createdFrom",
      "createdTo",
    ],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/stores/:storeId/products/export",
    idField: "id",
    searchHit: "ZXQ-PROD-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-PROD-HIT" },
    needsSeed: true,
  },
  {
    id: "modifier-groups",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/stores/:storeId/modifier-groups",
    scope: "CITY",
    actor: "admin",
    readPermission: "modifiers.read",
    sortAllowlist: ["name", "createdAt"],
    defaultSortBy: "createdAt",
    filters: ["productId", "status", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/stores/:storeId/modifier-groups/export",
    idField: "id",
    searchHit: "ZXQ-MOD-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-MOD-HIT" },
    needsSeed: true,
  },
  {
    id: "merchants",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/merchants",
    scope: "CITY",
    actor: "admin",
    readPermission: "merchants.read",
    sortAllowlist: ["createdAt", "displayName", "phone"],
    defaultSortBy: "createdAt",
    filters: ["status", "storeId", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/merchants/export",
    idField: "accountId",
    searchHit: "ZXQ-MERCH-HIT",
    andFilters: { status: "ACTIVE", search: "ZXQ-MERCH-HIT" },
    needsSeed: true,
  },
  {
    id: "admins",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/admins",
    scope: "GLOBAL",
    actor: "super",
    readPermission: "SUPER_ADMIN",
    sortAllowlist: ["createdAt", "displayName", "email"],
    defaultSortBy: "email",
    filters: ["cityId", "status", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/admins/export",
    idField: "accountId",
    searchHit: "admin.lists",
    andFilters: { search: "admin.lists" },
    needsSeed: true,
  },
  {
    id: "employees",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/employees",
    scope: "CITY",
    actor: "admin",
    readPermission: "CITY_ADMIN",
    sortAllowlist: ["createdAt", "displayName", "email"],
    defaultSortBy: "email",
    filters: ["status", "role", "permission", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/employees/export",
    idField: "accountId",
    searchHit: "ops.lists",
    andFilters: { status: "ACTIVE", search: "ops.lists" },
    needsSeed: true,
  },
  {
    id: "orders",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/orders",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.read",
    sortAllowlist: [
      "createdAt",
      "updatedAt",
      "deliveredAt",
      "status",
      "total",
      "orderNumber",
    ],
    defaultSortBy: "createdAt",
    filters: [
      "status",
      "storeId",
      "customerId",
      "driverId",
      "assignmentId",
      "custodyStatus",
      "createdFrom",
      "createdTo",
      "deliveredFrom",
      "deliveredTo",
      "cancelledFrom",
      "cancelledTo",
      "hasActiveHandoff",
      "hasActiveReturn",
      "paymentMethod",
      "paymentStatus",
      "totalMin",
      "totalMax",
      "storeCommissionRateMin",
      "storeCommissionRateMax",
    ],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/orders/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { status: "PENDING_STORE_APPROVAL", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "order-events",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/order-events",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.read",
    sortAllowlist: ["createdAt"],
    defaultSortBy: "createdAt",
    filters: ["orderId", "eventType", "source", "actorAccountId", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/order-events/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { source: "CUSTOMER_APP", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "order-assignments",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/order-assignments",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.read",
    sortAllowlist: ["assignedAt", "createdAt", "status"],
    defaultSortBy: "assignedAt",
    filters: [
      "orderId",
      "driverId",
      "status",
      "source",
      "closingReason",
      "assignedFrom",
      "assignedTo",
    ],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/order-assignments/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { status: "ASSIGNED", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "order-offer-rounds",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/order-offer-rounds",
    scope: "CITY",
    actor: "admin",
    readPermission: "order_offers.read",
    sortAllowlist: ["openedAt", "createdAt", "status"],
    defaultSortBy: "openedAt",
    filters: ["orderId", "status", "roundKind", "closingReason", "openedFrom", "openedTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/order-offer-rounds/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { status: "OPEN", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "order-offer-rounds-one",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/orders/:orderId/offer-rounds",
    scope: "CITY",
    actor: "admin",
    readPermission: "order_offers.read",
    sortAllowlist: ["openedAt", "createdAt", "status"],
    defaultSortBy: "openedAt",
    filters: ["status", "roundKind", "closingReason", "openedFrom", "openedTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/orders/:orderId/offer-rounds/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { status: "OPEN" },
    needsSeed: true,
  },
  {
    id: "order-handoffs",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/order-handoffs",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.read",
    sortAllowlist: ["createdAt", "status"],
    defaultSortBy: "createdAt",
    filters: ["orderId", "fromDriverId", "toDriverId", "status", "createdFrom", "createdTo"],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/order-handoffs/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { status: "PENDING", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "order-returns",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/order-returns",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.read",
    sortAllowlist: ["createdAt", "status"],
    defaultSortBy: "createdAt",
    filters: ["orderId", "driverId", "status", "createdFrom", "createdTo"],
    unimplementedFilters: [
      "trigger",
    ],
    exportPathTemplate: "/api/v1/dashboard/order-returns/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { status: "WAITING_FOR_DRIVER_RETURN", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "order-collections",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/order-collections",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.read",
    sortAllowlist: ["collectedAt", "expectedAmount", "collectedAmount", "differenceAmount"],
    defaultSortBy: "collectedAt",
    filters: [
      "orderId",
      "assignmentId",
      "driverId",
      "confirmationSource",
      "expectedMin",
      "expectedMax",
      "collectedMin",
      "collectedMax",
      "differenceMin",
      "differenceMax",
      "collectedFrom",
      "collectedTo",
    ],
    unimplementedFilters: [],
    exportPathTemplate: "/api/v1/dashboard/order-collections/export",
    idField: "id",
    searchHit: "ZXQ-ORD-HIT",
    andFilters: { confirmationSource: "DRIVER_APP", search: "ZXQ-ORD-HIT" },
    needsSeed: true,
  },
  {
    id: "assignment-candidates",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/drivers/assignment-candidates",
    scope: "CITY",
    actor: "admin",
    readPermission: "orders.assign",
    sortAllowlist: ["driverName", "activeOrderCount", "createdAt"],
    defaultSortBy: "driverName",
    filters: ["activeOrderCount"],
    unimplementedFilters: [
      "eligibilityStatus",
      "workStatus",
      "hasLocation",
      "lastSeenFrom",
      "lastSeenTo",
    ],
    exportPathTemplate: "/api/v1/dashboard/drivers/assignment-candidates/export",
    idField: "driverId",
    searchHit: "+964770",
    andFilters: { activeOrderCount: "0" },
    needsSeed: true,
  },
  {
    id: "delivery-pricing-versions",
    method: "GET",
    pathTemplate: "/api/v1/dashboard/cities/:cityId/delivery-pricing/versions",
    scope: "GLOBAL",
    actor: "super",
    readPermission: "SUPER_ADMIN",
    sortAllowlist: ["version", "createdAt", "activatedAt", "status"],
    defaultSortBy: "version",
    filters: [
      "status",
      "createdByAccountId",
      "createdFrom",
      "createdTo",
      "activatedFrom",
      "activatedTo",
    ],
    unimplementedFilters: [],
    exportPathTemplate:
      "/api/v1/dashboard/cities/:cityId/delivery-pricing/versions/export",
    idField: "id",
    searchHit: "1",
    andFilters: { status: "DRAFT" },
    needsSeed: true,
  },
] as const;

export const DASHBOARD_LIST_COUNT = DASHBOARD_LIST_ENDPOINTS.length;

export const DASHBOARD_LIST_GAPS = {
  assignmentCandidates:
    "eligibilityStatus, workStatus, hasLocation, and lastSeen* live in Redis driver runtime, not PostgreSQL. They are response fields only and must not be list filters.",
  orderReturns:
    "order_return_workflows has no trigger column. A trigger filter is not implemented.",
} as const;
