import { afterAll,beforeAll,describe,expect,test } from "bun:test";
import { SQL } from "bun";
import type { AppConfig } from "../../src/config/env";
import { applyMigrations } from "../../src/db/migration-runner";
import { createAuthModule,type AuthModule } from "../../src/modules/auth/auth-module";
import { customerContext,dashboardContext,driverContext } from "../../src/modules/auth/core/context";
import { TestOtpDelivery } from "../../src/modules/auth/phone/delivery";
import { InMemoryRateLimiter } from "../../src/modules/auth/rate-limit/rate-limiter";
import { Argon2PasswordHasher } from "../../src/modules/auth/staff/password";

const adminUrl=process.env.TEST_ADMIN_DATABASE_URL;if(!adminUrl)throw new Error("TEST_ADMIN_DATABASE_URL is required");const parsed=new URL(adminUrl);if(!["localhost","127.0.0.1"].includes(parsed.hostname)||/prod/i.test(parsed.pathname))throw new Error("Unsafe integration database");
const config:AppConfig={nodeEnv:"test",host:"127.0.0.1",port:3000,logLevel:"error",databaseUrl:adminUrl,databasePoolSize:5,databaseConnectionTimeoutMs:5000,gracefulShutdownTimeoutMs:5000,redisUrl:"redis://localhost:6380",otpDeliveryAdapter:"test",secretVerifierKey:"integration-verifier-key-at-least-32-characters",secretVerifierKeyVersion:"v1",jwtIssuer:"integration",jwtKeyId:"integration-v1",jwtPrivateKeyBase64:"MC4CAQAwBQYDK2VwBCIEIOhYjslG5wawzghWHcQbYCMjFp8kzMYLVFZoKEOBzTA4",jwtPublicKeyBase64:"MCowBQYDK2VwAyEA+ly2CeP4N1AQ5vNUEt226L6GtOMU/uLE2rjFfo4OBCE=",accessTokenLifetimeSeconds:600,argon2MemoryCost:19456,argon2TimeCost:2,argon2Parallelism:1};

describe("M2 separated authentication",()=>{const dbName=`pip_pip_v3_test_${crypto.randomUUID().replaceAll("-","")}`;let admin:SQL,client:SQL,delivery:TestOtpDelivery,auth:AuthModule;let clock=Date.now();const advance=()=>{clock+=3_600_001;};
beforeAll(async()=>{admin=new SQL(adminUrl,{max:1});await admin.unsafe(`create database "${dbName}"`);const url=new URL(adminUrl);url.pathname=`/${dbName}`;client=new SQL(url.toString(),{max:12});await applyMigrations(client);delivery=new TestOtpDelivery();auth=createAuthModule(client,new InMemoryRateLimiter(()=>clock),delivery,config);},30000);
afterAll(async()=>{if(client)await client.close();if(admin){await admin.unsafe(`drop database if exists "${dbName}" with(force)`);await admin.close();}});

const customerLogin=async(phone:string,device:string)=>{advance();const id=await auth.customer.requestOtp({phone,ip:`request-${device}`,requestId:`request-${device}`});return auth.customer.verifyOtp({challengeId:id,otp:delivery.deliveries.at(-1)!.otp,deviceId:device,deviceName:device,ip:`verify-${device}`,requestId:`verify-${device}`});};
const createDriver=async(phone:string,code:string|null,status:"ACTIVE"|"SUSPENDED"="ACTIVE")=>{const[account]=await client<{id:string}[]>`insert into accounts default values returning id`;await client`insert into account_phones(account_id,phone_e164,verified_at,is_primary)values(${account!.id},${phone},now(),true)`;const[reviewer]=await client<{id:string}[]>`insert into accounts default values returning id`;const[application]=await client<{id:string}[]>`insert into driver_applications(account_id,status,decided_at,decided_by_account_id)values(${account!.id},'APPROVED',now(),${reviewer!.id})returning id`;const hasher=new Argon2PasswordHasher({memoryCost:19456,timeCost:2,parallelism:1});await client`insert into driver_profiles(account_id,approved_application_id,operational_status,driver_photo_object_key,access_code_hash)values(${account!.id},${application!.id},${status},'photo',${code?await hasher.hash(code):null})`;return account!.id;};

test("Customer OTP request creates no account, replaces prior challenge, and is Customer-bound",async()=>{const phone="+9647702000000";const first=await auth.customer.requestOtp({phone,ip:"otp1",requestId:"text-request-id"});expect(Number((await client<{count:string}[]>`select count(*)::text count from accounts`)[0]!.count)).toBe(0);advance();const second=await auth.customer.requestOtp({phone,ip:"otp2",requestId:"otp2"});const[old]=await client<{invalidated_at:Date|null;replacement_challenge_id:string|null;application_type:string}[]>`select invalidated_at,replacement_challenge_id,application_type::text application_type from otp_challenges where id=${first}`;expect(old).toMatchObject({replacement_challenge_id:second,application_type:"CUSTOMER_APP"});expect(old!.invalidated_at).not.toBeNull();});
test("Customer OTP attempts exhaust at five and concurrent consume has one winner",async()=>{advance();const failed=await auth.customer.requestOtp({phone:"+9647702000001",ip:"attempt",requestId:"attempt"});for(let n=0;n<5;n++)await expect(auth.customer.verifyOtp({challengeId:failed,otp:"000000",deviceName:"x",ip:`a${n}`,requestId:`a${n}`})).rejects.toThrow();expect((await client<{attempt_count:number}[]>`select attempt_count from otp_challenges where id=${failed}`)[0]!.attempt_count).toBe(5);advance();const id=await auth.customer.requestOtp({phone:"+9647702000002",ip:"race",requestId:"race"}),otp=delivery.deliveries.at(-1)!.otp;const outcomes=await Promise.allSettled([0,1].map(n=>auth.customer.verifyOtp({challengeId:id,otp,deviceName:`r${n}`,ip:`r${n}`,requestId:`r${n}`})));expect(outcomes.filter(x=>x.status==="fulfilled").length).toBe(1);});
test("Customer limit is five with deterministic oldest revocation",async()=>{const phone="+9647702000003";let account="";for(let n=0;n<6;n++){const result=await customerLogin(phone,`c${n}`);account=(await client<{account_id:string}[]>`select account_id from sessions where id=${result.session_id}`)[0]!.account_id;}const rows=await client<{revoked_at:Date|null}[]>`select revoked_at from sessions where account_id=${account} and application_type='CUSTOMER_APP' order by created_at,id`;expect(rows.filter(x=>!x.revoked_at).length).toBe(5);expect(rows[0]!.revoked_at).not.toBeNull();});
test("Driver uses a 6-12 digit string code, preserves leading zeroes, and has no OTP",async()=>{const phone="+9647702000010",account=await createDriver(phone,"001927");for(const code of["12345","1234567890123","١٢٣٤٥٦","12 3456","+123456"])await expect(auth.driver.login({phone,code,deviceName:"d",ip:`bad-${code}`,requestId:`bad-${code}`})).rejects.toThrow();await expect(auth.driver.login({phone,code:"999999",deviceName:"d",ip:"wrong",requestId:"wrong"})).rejects.toThrow();const login=await auth.driver.login({phone,code:"001927",deviceName:"d",ip:"good",requestId:"good"});expect(login.application_type).toBe("DRIVER_APP");expect((await client<{authentication_method:string}[]>`select authentication_method::text authentication_method from sessions where id=${login.session_id}`)[0]!.authentication_method).toBe("DRIVER_ACCESS_CODE");expect(account).toBeTruthy();});
test("Missing code, inactive Driver, and unknown phone fail generically",async()=>{const missing="+9647702000011",inactive="+9647702000012";await createDriver(missing,null);await createDriver(inactive,"123456","SUSPENDED");for(const[caseName,phone]of[["missing-code",missing],["inactive-driver",inactive],["unknown-phone","+9647702999999"]]as const){const outcome=await auth.driver.login({phone,code:"123456",deviceName:"d",ip:phone,requestId:caseName}).then(()=>({publicCode:"LOGIN_SUCCEEDED"}),error=>error as {publicCode?:string});expect(outcome).toMatchObject({publicCode:"INVALID_CREDENTIALS"});}});
test("Driver replacement leaves one Driver session and preserves Customer sessions",async()=>{const phone="+9647702000013",account=await createDriver(phone,"123456");await client`insert into customer_profiles(account_id)values(${account})`;await client`insert into sessions(account_id,application_type,authentication_method,device_name,absolute_expires_at)values(${account},'CUSTOMER_APP','PHONE_OTP','customer',now()+interval '1 day')`;await auth.driver.login({phone,code:"123456",deviceName:"d1",ip:"d1",requestId:"d1"});await auth.driver.login({phone,code:"123456",deviceName:"d2",ip:"d2",requestId:"d2"});expect(Number((await client<{count:string}[]>`select count(*)::text count from sessions where account_id=${account} and application_type='DRIVER_APP' and revoked_at is null`)[0]!.count)).toBe(1);expect(Number((await client<{count:string}[]>`select count(*)::text count from sessions where account_id=${account} and application_type='CUSTOMER_APP' and revoked_at is null`)[0]!.count)).toBe(1);});
test("Dashboard login is generic and limits active sessions to three",async()=>{const[account]=await client<{id:string}[]>`insert into accounts default values returning id`;await client`insert into account_emails(account_id,email_original,email_normalized,verified_at,is_primary)values(${account!.id},'Staff@Example.com','staff@example.com',now(),true)`;await client`insert into staff_profiles(account_id,status)values(${account!.id},'ACTIVE')`;const[role]=await client<{id:string}[]>`select id from roles where code='SUPPORT'`;await client`insert into account_roles(account_id,role_id,granted_by_account_id)values(${account!.id},${role!.id},${account!.id})`;const hash=await new Argon2PasswordHasher({memoryCost:19456,timeCost:2,parallelism:1}).hash("fixed staff password");await client`insert into password_credentials(account_id,argon2id_hash)values(${account!.id},${hash})`;await expect(auth.dashboard.login({email:"missing@example.com",password:"wrong password value",deviceName:"x",ip:"missing",requestId:"missing"})).rejects.toThrow();let last;for(let n=0;n<4;n++)last=await auth.dashboard.login({email:"STAFF@example.com",password:"fixed staff password",deviceName:`s${n}`,ip:`s${n}`,requestId:`s${n}`});expect(Number((await client<{count:string}[]>`select count(*)::text count from sessions where account_id=${account!.id} and application_type='DASHBOARD' and revoked_at is null`)[0]!.count)).toBe(3);expect(last!.application_type).toBe("DASHBOARD");});
test("JWT and refresh tokens are audience-bound without consuming cross-application attempts",async()=>{const issued=await customerLogin("+9647702000020","aud");await auth.sessions.authenticate(issued.access_token,customerContext,"ok");await expect(auth.sessions.authenticate(issued.access_token,driverContext,"wrong-driver")).rejects.toThrow();await expect(auth.sessions.authenticate(issued.access_token,dashboardContext,"wrong-dashboard")).rejects.toThrow();await expect(auth.sessions.refresh(issued.refresh_token,driverContext,"cross","cross")).rejects.toThrow();const rotated=await auth.sessions.refresh(issued.refresh_token,customerContext,"correct","correct");expect(rotated.refresh_token).not.toBe(issued.refresh_token);});
test("Concurrent refresh has one winner and Customer reuse remains Customer-scoped",async()=>{const issued=await customerLogin("+9647702000021","refresh");const outcomes=await Promise.allSettled([auth.sessions.refresh(issued.refresh_token,customerContext,"r1","r1"),auth.sessions.refresh(issued.refresh_token,customerContext,"r2","r2")]);expect(outcomes.filter(x=>x.status==="fulfilled").length).toBe(1);expect(outcomes.filter(x=>x.status==="rejected").length).toBe(1);});
test("Application-scoped logout-all and ownership do not cross boundaries",async()=>{const phone="+9647702000022",account=await createDriver(phone,"123456");await client`insert into customer_profiles(account_id)values(${account})`;const customer=await client<{id:string}[]>`insert into sessions(account_id,application_type,authentication_method,device_name,absolute_expires_at)values(${account},'CUSTOMER_APP','PHONE_OTP','c',now()+interval '1 day')returning id`;const driver=await auth.driver.login({phone,code:"123456",deviceName:"d",ip:"scope",requestId:"scope"});const identity={accountId:account,sessionId:customer[0]!.id,applicationType:"CUSTOMER_APP" as const};await auth.sessions.logoutAll(identity,customerContext,"logout-scope");expect((await client<{revoked_at:Date|null}[]>`select revoked_at from sessions where id=${driver.session_id}`)[0]!.revoked_at).toBeNull();const[other]=await client<{id:string}[]>`insert into accounts default values returning id`;await expect(auth.sessions.revoke({accountId:other!.id,sessionId:crypto.randomUUID(),applicationType:"CUSTOMER_APP"},customer[0]!.id,customerContext,"owner")).rejects.toThrow();});
test("Audit request IDs remain textual and metadata contains no credentials",async()=>{const[row]=await client<{request_correlation_id:string;redacted_metadata:unknown}[]>`select request_correlation_id,redacted_metadata from audit_logs where request_correlation_id='text-request-id'`;expect(row!.request_correlation_id).toBe("text-request-id");expect(JSON.stringify(row!.redacted_metadata)).not.toMatch(/password|code|otp|token/i);});
});
