import { afterAll,beforeAll,describe,expect,test } from "bun:test";
import { customerContext } from "../../src/modules/auth/core/context";
import { createActiveCity,createIntegrationHarness,jsonRequest,type IntegrationHarness } from "./helpers";

describe("Customer server-side Cart",()=>{
  let h:IntegrationHarness,city="",city2="",store="",store2="",product="",product2="",unavailable="",modProduct="",opt1="",opt2="",opt3="",customer="",otherCustomer="",modCustomer="",token="";
  beforeAll(async()=>{
    h=await createIntegrationHarness({databasePrefix:"pip_pip_v3_cart"}); city=await createActiveCity(h.client,"Cart City");city2=await createActiveCity(h.client,"Cart City 2");
    const [actor]=await h.client<{id:string}[]>`insert into accounts default values returning id`;const actorId=actor!.id;
    const makeStore=async(cityId:string,name:string)=>{const [media]=await h.client<{id:string}[]>`insert into media_assets(city_id,purpose,visibility,status,object_key,original_name,expected_content_type,expected_size_bytes,created_by_account_id,upload_expires_at) values(${cityId},'CATEGORY_IMAGE','PUBLIC','PENDING_UPLOAD',${crypto.randomUUID()},'x.png','image/png',1,${actorId},now()+interval '1 hour') returning id`;const [main]=await h.client<{id:string}[]>`insert into main_categories(city_id,name,image_asset_id,status,created_by_account_id) values(${cityId},${name},${media!.id},'ACTIVE',${actorId}) returning id`;const [logo]=await h.client<{id:string}[]>`insert into media_assets(city_id,purpose,visibility,status,object_key,original_name,expected_content_type,expected_size_bytes,created_by_account_id,upload_expires_at) values(${cityId},'STORE_LOGO','PUBLIC','PENDING_UPLOAD',${crypto.randomUUID()},'l.png','image/png',1,${actorId},now()+interval '1 hour') returning id`;const [s]=await h.client<{id:string}[]>`insert into stores(city_id,main_category_id,name,phone,address,location,logo_asset_id,status,created_by_account_id) values(${cityId},${main!.id},${name},${`07${crypto.randomUUID().slice(0,8)}`},'x',st_setsrid(st_makepoint(44,33),4326),${logo!.id},'ACTIVE',${actorId}) returning id`;return s!.id};
    store=await makeStore(city,"متجر");store2=await makeStore(city,"متجر ثان");
    const makeProduct=async(storeId:string,name:string,available=true)=>{const [p]=await h.client<{id:string}[]>`insert into products(store_id,city_id,name,base_price,is_available,status,created_by_account_id) values(${storeId},${city},${name},1000,${available},'ACTIVE',${actorId}) returning id`;return p!.id};
    product=await makeProduct(store,"منتج");product2=await makeProduct(store2,"منتج ثان");unavailable=await makeProduct(store,"غير متاح",false);
    const [group]=await h.client<{id:string}[]>`insert into modifier_groups(store_id,city_id,name,min_select,max_select,status,created_by_account_id) values(${store},${city},'إضافات',1,4,'ACTIVE',${actorId}) returning id`;
    const makeOption=async(name:string)=>{const [o]=await h.client<{id:string}[]>`insert into modifier_options(store_id,city_id,modifier_group_id,name,status) values(${store},${city},${group!.id},${name},'ACTIVE') returning id`;return o!.id};opt1=await makeOption("افتراضي");opt2=await makeOption("جبن");opt3=await makeOption("صلصة");
    const [mp]=await h.client<{id:string}[]>`insert into products(store_id,city_id,modifier_group_id,name,base_price,status,created_by_account_id) values(${store},${city},${group!.id},'مع إضافات',2000,'ACTIVE',${actorId}) returning id`;modProduct=mp!.id;
    await h.client`insert into product_modifier_options(product_id,store_id,city_id,modifier_option_id,price,is_default,max_quantity) values(${modProduct},${store},${city},${opt1},0,true,1),(${modProduct},${store},${city},${opt2},250,false,2),(${modProduct},${store},${city},${opt3},100,false,1)`;
    const [a]=await h.client<{id:string}[]>`insert into accounts default values returning id`;customer=a!.id;await h.client`insert into customer_profiles(account_id) values(${customer})`;
    const [b]=await h.client<{id:string}[]>`insert into accounts default values returning id`;otherCustomer=b!.id;await h.client`insert into customer_profiles(account_id) values(${otherCustomer})`;
    const [m]=await h.client<{id:string}[]>`insert into accounts default values returning id`;modCustomer=m!.id;await h.client`insert into customer_profiles(account_id) values(${modCustomer})`;
    const created=await h.client.begin(tx=>h.auth.sessions.create(tx,customer,customerContext,"PHONE_OTP",undefined,"cart-test"));token=(await h.auth.sessions.result(customer,created,customerContext)).access_token;
  });
  afterAll(()=>h?.close());

  test("public Catalog remains anonymous while Cart requires Customer auth",async()=>{expect((await h.app.handle(jsonRequest(`/api/v1/public/stores/${store}/products`,{headers:{"X-City-Id":city}}))).status).toBe(200);expect((await h.app.handle(jsonRequest("/api/v1/mobile/customer/cart",{headers:{"X-City-Id":city}}))).status).toBe(401)});
  test("Cart requires X-City-Id",async()=>expect((await h.app.handle(jsonRequest("/api/v1/mobile/customer/cart",{token}))).status).toBe(400));
  test("a never-created Cart follows detail-resource not-found convention",async()=>expect((await h.app.handle(jsonRequest("/api/v1/mobile/customer/cart",{token,headers:{"X-City-Id":city}}))).status).toBe(404));
  test("adds, prices, merges identical configurations, and enforces one active Cart",async()=>{let cart=await h.cart.add(customer,city,store,{productId:product,quantity:2});expect(cart.itemsSubtotal).toBe(2000);expect(cart.items[0].currentLineTotal).toBe(2000);cart=await h.cart.add(customer,city,store,{productId:product,quantity:3,modifierSelections:[]});expect(cart.items).toHaveLength(1);expect(cart.items[0].quantity).toBe(5);const rows=await h.client<{count:number}[]>`select count(*)::int count from carts where customer_account_id=${customer} and status='ACTIVE'`;expect(rows[0]!.count).toBe(1)});
  test("cross-Store conflict preserves old Cart",async()=>{expect(h.cart.add(customer,city,store2,{productId:product2,quantity:1})).rejects.toMatchObject({publicCode:"CART_STORE_CONFLICT"});expect((await h.cart.get(customer,city)).store.id).toBe(store)});
  test("wrong City and wrong Customer cannot expose the Cart",async()=>{expect(h.cart.get(customer,city2)).rejects.toMatchObject({publicCode:"CART_NOT_FOUND"});expect(h.cart.get(otherCustomer,city)).rejects.toMatchObject({publicCode:"CART_NOT_FOUND"})});
  test("unavailable and cross-Store Products cannot be newly added",async()=>{expect(h.cart.add(customer,city,store,{productId:unavailable,quantity:1})).rejects.toMatchObject({publicCode:"PRODUCT_NOT_FOUND"});expect(h.cart.add(customer,city,store,{productId:product2,quantity:1})).rejects.toMatchObject({publicCode:"PRODUCT_NOT_FOUND"})});
  test("quantity validation rejects zero and over 99",async()=>{expect(h.cart.update(customer,city,(await h.cart.get(customer,city)).items[0].id,0)).rejects.toMatchObject({publicCode:"INVALID_CART_QUANTITY"});expect(h.cart.add(customer,city,store,{productId:product,quantity:99})).rejects.toMatchObject({publicCode:"INVALID_CART_QUANTITY"})});
  test("price changes in either direction expose current authoritative totals",async()=>{await h.client`update products set base_price=1200 where id=${product}`;let cart=await h.cart.get(customer,city);expect(cart.priceChanged).toBe(true);expect(cart.items[0].currentUnitPrice).toBe(1200);await h.client`update products set base_price=800 where id=${product}`;cart=await h.cart.get(customer,city);expect(cart.priceChanged).toBe(true);expect(cart.items[0].currentUnitPrice).toBe(800)});
  test("Catalog invalidation preserves an Item and marks it non-orderable",async()=>{await h.client`update products set is_available=false where id=${product}`;const cart=await h.cart.get(customer,city);expect(cart.items).toHaveLength(1);expect(cart.items[0].isOrderable).toBe(false);await h.client`update products set is_available=true,base_price=1000 where id=${product}`});
  test("atomic replace changes Store and failed replacement preserves it",async()=>{let cart=await h.cart.replace(customer,city,store2,{productId:product2,quantity:1});expect(cart.store.id).toBe(store2);expect(cart.items).toHaveLength(1);expect(h.cart.replace(customer,city,store,{productId:unavailable,quantity:1})).rejects.toMatchObject({publicCode:"PRODUCT_NOT_FOUND"});cart=await h.cart.get(customer,city);expect(cart.store.id).toBe(store2)});
  test("delete-last and clear preserve the active Cart",async()=>{let cart=await h.cart.get(customer,city);cart=await h.cart.remove(customer,city,cart.items[0].id);expect(cart.items).toHaveLength(0);cart=await h.cart.add(customer,city,store2,{productId:product2,quantity:1});cart=await h.cart.clear(customer,city);expect(cart.items).toHaveLength(0);expect(cart.id).toBeTruthy()});
  test("PAUSED Cart stays readable and rejects mutations",async()=>{await h.client`update stores set order_acceptance_status='PAUSED' where id=${store2}`;const cart=await h.cart.get(customer,city);expect(cart.store.orderAcceptanceStatus).toBe("PAUSED");expect(h.cart.add(customer,city,store2,{productId:product2,quantity:1})).rejects.toMatchObject({publicCode:"STORE_NOT_ACCEPTING_ORDERS"})});
  test("defaults, modifier pricing, canonical ordering, and distinct configurations",async()=>{let cart=await h.cart.add(modCustomer,city,store,{productId:modProduct,quantity:2,modifierSelections:[{modifierOptionId:opt3},{modifierOptionId:opt2,quantity:2}]});expect(cart.items[0].currentModifiersPrice).toBe(600);expect(cart.items[0].currentLineTotal).toBe(5200);cart=await h.cart.add(modCustomer,city,store,{productId:modProduct,quantity:1,modifierSelections:[{modifierOptionId:opt2,quantity:2},{modifierOptionId:opt3}]});expect(cart.items).toHaveLength(1);expect(cart.items[0].quantity).toBe(3);cart=await h.cart.add(modCustomer,city,store,{productId:modProduct,quantity:1,modifierSelections:[]});expect(cart.items).toHaveLength(2);expect(cart.items.find((i:any)=>i.modifierSelections.length===1)?.modifierSelections[0].modifierOptionId).toBe(opt1)});
  test("invalid, duplicate, over-max, and unavailable Modifier selections are rejected",async()=>{expect(h.cart.add(modCustomer,city,store,{productId:modProduct,quantity:1,modifierSelections:[{modifierOptionId:opt2},{modifierOptionId:opt2}]})).rejects.toMatchObject({publicCode:"INVALID_MODIFIER_SELECTION"});expect(h.cart.add(modCustomer,city,store,{productId:modProduct,quantity:1,modifierSelections:[{modifierOptionId:opt2,quantity:3}]})).rejects.toMatchObject({publicCode:"INVALID_MODIFIER_SELECTION"});await h.client`update modifier_options set is_available=false where id=${opt3}`;expect(h.cart.add(modCustomer,city,store,{productId:modProduct,quantity:1,modifierSelections:[{modifierOptionId:opt3}]})).rejects.toMatchObject({publicCode:"INVALID_MODIFIER_SELECTION"})});
  test("existing unavailable Modifier selections remain visible and invalid",async()=>{const cart=await h.cart.get(modCustomer,city);const affected=cart.items.find((i:any)=>i.modifierSelections.some((s:any)=>s.modifierOptionId===opt3));expect(affected).toBeTruthy();expect(affected.isOrderable).toBe(false)});
  test("concurrent first identical adds converge without duplicate logical Items",async()=>{await h.client`update stores set order_acceptance_status='ACCEPTING' where id=${store2}`;await Promise.all([h.cart.add(otherCustomer,city,store2,{productId:product2,quantity:2}),h.cart.add(otherCustomer,city,store2,{productId:product2,quantity:3})]);const cart=await h.cart.get(otherCustomer,city);expect(cart.items).toHaveLength(1);expect(cart.items[0].quantity).toBe(5)});
});
