import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import type { AuthIdentity } from "../../src/modules/auth/sessions/session-service";
import { createActiveCity, createIntegrationHarness, type IntegrationHarness } from "./helpers";
import { RouteNotFoundError, RoutingProviderError } from "../../src/modules/delivery-pricing/routing-provider";

let h:IntegrationHarness,cityId:string,superId:string,customerId:string,storeId:string;
const superIdentity=():AuthIdentity=>({accountId:superId,sessionId:crypto.randomUUID(),applicationType:"DASHBOARD",roles:["SUPER_ADMIN"],scopeType:"GLOBAL",cityId:null,storeId:null});
const input={baseFee:1000,includedDistanceMeters:1000,pricePerKm:500,roundingStep:250,maximumDeliveryDistanceMeters:10000,routingFallbackEnabled:true,fallbackOnNoRoute:true,fallbackOnProviderFailure:true,fallbackExtraDistanceMeters:300};

describe("versioned delivery pricing persistence",()=>{
  beforeAll(async()=>{h=await createIntegrationHarness({databasePrefix:"delivery_pricing"});cityId=await createActiveCity(h.client);const [a]=await h.client<{id:string}[]>`insert into accounts default values returning id`;superId=a!.id;const [c]=await h.client<{id:string}[]>`insert into accounts default values returning id`;customerId=c!.id;
    const [media]=await h.client<{id:string}[]>`insert into media_assets(city_id,purpose,visibility,status,object_key,original_name,expected_content_type,expected_size_bytes,verified_content_type,verified_size_bytes,created_by_account_id,upload_expires_at,ready_at,attached_at) values(${cityId},'CATEGORY_IMAGE','PUBLIC','READY',${crypto.randomUUID()},'x.png','image/png',1,'image/png',1,${superId},now(),now(),now()) returning id`;
    const [category]=await h.client<{id:string}[]>`insert into main_categories(city_id,name,image_asset_id,status,created_by_account_id) values(${cityId},'مطاعم',${media!.id},'ACTIVE',${superId}) returning id`;
    const [store]=await h.client<{id:string}[]>`insert into stores(city_id,main_category_id,name,phone,address,location,logo_asset_id,status,order_acceptance_status,created_by_account_id) values(${cityId},${category!.id},'Store','+9647000000000','Address',ST_SetSRID(ST_MakePoint(44.4,33.3),4326),${media!.id},'ACTIVE','PAUSED',${superId}) returning id`;storeId=store!.id;
    const [zone]=await h.client<{id:string}[]>`insert into zones(city_id,name,boundary,status) values(${cityId},'Delivery',ST_GeomFromText('POLYGON((44.0 33.0,45.0 33.0,45.0 34.0,44.0 34.0,44.0 33.0))',4326),'ACTIVE') returning id`;
    await h.client`insert into store_zones(store_id,zone_id,city_id) values(${storeId},${zone!.id},${cityId})`;
  });
  afterAll(async()=>h.close());
  test("creation is DRAFT and never auto-activates",async()=>{const row=await h.deliveryPricing.create(superIdentity(),cityId,input);expect(row.status).toBe("DRAFT");expect(row.version).toBe(1);await expect(h.deliveryPricing.activeForSuper(superIdentity(),cityId)).rejects.toMatchObject({publicCode:"ACTIVE_DELIVERY_PRICING_NOT_FOUND"});});
  test("concurrent creation allocates unique increasing versions",async()=>{const rows=await Promise.all([h.deliveryPricing.create(superIdentity(),cityId,input),h.deliveryPricing.create(superIdentity(),cityId,input)]);expect(rows.map(x=>x.version).sort()).toEqual([2,3]);});
  test("activation is atomic and database keeps one active",async()=>{const versions=await h.deliveryPricing.list(superIdentity(),cityId);const first=versions.find(x=>x.version===1)!;const second=versions.find(x=>x.version===2)!;await h.deliveryPricing.activate(superIdentity(),cityId,first.id);await h.deliveryPricing.activate(superIdentity(),cityId,second.id);const all=await h.deliveryPricing.list(superIdentity(),cityId);expect(all.filter(x=>x.status==="ACTIVE")).toHaveLength(1);expect(all.find(x=>x.id===first.id)?.status).toBe("INACTIVE");});
  test("INACTIVE version cannot be reactivated",async()=>{const old=(await h.deliveryPricing.list(superIdentity(),cityId)).find(x=>x.version===1)!;await expect(h.deliveryPricing.activate(superIdentity(),cityId,old.id)).rejects.toMatchObject({publicCode:"DELIVERY_PRICING_REACTIVATION_FORBIDDEN"});});
  test("contradictory fallback configuration is rejected",async()=>{await expect(h.deliveryPricing.create(superIdentity(),cityId,{...input,routingFallbackEnabled:false})).rejects.toMatchObject({publicCode:"VALIDATION_FAILED"});});
  test("PAUSED public Store estimates with routed distance unchanged",async()=>{h.routingProvider.setResult({distanceMeters:2500.25,durationSeconds:301.5});const result=await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}});expect(result).toMatchObject({deliveryAvailable:true,distanceSource:"ROUTE",pricingDistanceMeters:2500.25,routeDistanceMeters:2500.25,deliveryFee:2000,store:{orderAcceptanceStatus:"PAUSED"}});});
  test("NoRoute uses named straight-line fallback",async()=>{h.routingProvider.setResult(new RouteNotFoundError());const result=await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}});expect(result.distanceSource).toBe("STRAIGHT_LINE_FALLBACK");expect(result.fallbackReason).toBe("NO_ROUTE");expect(result.pricingDistanceMeters).toBe(result.straightLineDistanceMeters+300);});
  test("provider failure uses configured fallback",async()=>{h.routingProvider.setResult(new RoutingProviderError());const result=await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}});expect(result.fallbackReason).toBe("PROVIDER_FAILURE");});
  test("outside Zone is unavailable and never calls routing",async()=>{const calls=h.routingProvider.calls;const result=await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:35,longitude:46}});expect(result).toMatchObject({deliveryAvailable:false,reason:"ADDRESS_OUTSIDE_DELIVERY_ZONE",deliveryFee:null,distanceSource:null});expect(h.routingProvider.calls).toBe(calls);});
  test("requires exactly one destination mode",async()=>{await expect(h.deliveryPricing.estimate(customerId,cityId,{storeId})).rejects.toMatchObject({publicCode:"VALIDATION_FAILED"});await expect(h.deliveryPricing.estimate(customerId,cityId,{storeId,addressId:crypto.randomUUID(),destination:{latitude:33.3,longitude:44.4}})).rejects.toMatchObject({publicCode:"VALIDATION_FAILED"});});
  test("address ownership and City scope are non-disclosing",async()=>{await expect(h.deliveryPricing.estimate(customerId,cityId,{storeId,addressId:crypto.randomUUID()})).rejects.toMatchObject({publicCode:"ADDRESS_NOT_FOUND"});});
});
