import { afterEach,beforeEach,describe,expect,test } from "bun:test";
import type { AuthIdentity } from "../../src/modules/auth/sessions/session-service";
import { fakeRoutingError } from "../../src/modules/delivery-pricing/routing-provider";
import { createActiveCity,createIntegrationHarness,createStaffAccount,jsonRequest,type IntegrationHarness } from "./helpers";

let h:IntegrationHarness,cityId:string,superId:string,customerId:string,storeId:string;
const identity=():AuthIdentity=>({accountId:superId,sessionId:null as unknown as string,applicationType:"DASHBOARD",roles:["SUPER_ADMIN"],scopeType:"GLOBAL",cityId:null,storeId:null});
const input={baseFee:1000,includedDistanceMeters:1000,pricePerKm:500,roundingStep:250,maximumDeliveryDistanceMeters:10000,routingFallbackEnabled:true,fallbackOnNoRoute:true,fallbackOnProviderFailure:true,fallbackExtraDistanceMeters:300};
async function activate(values=input){const row=await h.deliveryPricing.create(identity(),cityId,values);await h.deliveryPricing.activate(identity(),cityId,row.id);return row;}

describe("versioned delivery pricing",()=>{
  beforeEach(async()=>{h=await createIntegrationHarness({databasePrefix:"delivery_pricing"});cityId=await createActiveCity(h.client);const[a]=await h.client<{id:string}[]>`insert into accounts default values returning id`;superId=a!.id;const[c]=await h.client<{id:string}[]>`insert into accounts default values returning id`;customerId=c!.id;const[m]=await h.client<{id:string}[]>`insert into media_assets(city_id,purpose,visibility,status,object_key,original_name,expected_content_type,expected_size_bytes,verified_content_type,verified_size_bytes,created_by_account_id,upload_expires_at,ready_at,attached_at) values(${cityId},'CATEGORY_IMAGE','PUBLIC','READY',${crypto.randomUUID()},'x.png','image/png',1,'image/png',1,${superId},now(),now(),now()) returning id`;const[cat]=await h.client<{id:string}[]>`insert into main_categories(city_id,name,image_asset_id,status,created_by_account_id) values(${cityId},'مطاعم',${m!.id},'ACTIVE',${superId}) returning id`;const[s]=await h.client<{id:string}[]>`insert into stores(city_id,main_category_id,name,phone,address,location,logo_asset_id,status,order_acceptance_status,created_by_account_id) values(${cityId},${cat!.id},'Store','+9647000000000','Address',ST_SetSRID(ST_MakePoint(44.4,33.3),4326),${m!.id},'ACTIVE','PAUSED',${superId}) returning id`;storeId=s!.id;const[z]=await h.client<{id:string}[]>`insert into zones(city_id,name,boundary,status) values(${cityId},'Delivery',ST_GeomFromText('POLYGON((44 33,45 33,45 34,44 34,44 33))',4326),'ACTIVE') returning id`;await h.client`insert into store_zones(store_id,zone_id,city_id) values(${storeId},${z!.id},${cityId})`;});
  afterEach(async()=>h.close());
  test("creation is explicit DRAFT",async()=>{const row=await h.deliveryPricing.create(identity(),cityId,input);expect(row).toMatchObject({status:"DRAFT",version:1,activationRevision:null});await expect(h.deliveryPricing.activeForSuper(identity(),cityId)).rejects.toMatchObject({publicCode:"ACTIVE_DELIVERY_PRICING_NOT_FOUND"});});
  test("concurrent creation allocates sequential versions",async()=>{const rows=await Promise.all([h.deliveryPricing.create(identity(),cityId,input),h.deliveryPricing.create(identity(),cityId,input)]);expect(rows.map(x=>x.version).sort()).toEqual([1,2]);});
  test("activation retires previous and INACTIVE is terminal",async()=>{const a=await h.deliveryPricing.create(identity(),cityId,input),b=await h.deliveryPricing.create(identity(),cityId,input);await h.deliveryPricing.activate(identity(),cityId,a.id);await h.deliveryPricing.activate(identity(),cityId,b.id);const all=await h.deliveryPricing.list(identity(),cityId);expect(all.filter(x=>x.status==="ACTIVE")).toHaveLength(1);expect(all.find(x=>x.id===a.id)?.status).toBe("INACTIVE");await expect(h.deliveryPricing.activate(identity(),cityId,a.id)).rejects.toMatchObject({publicCode:"DELIVERY_PRICING_REACTIVATION_FORBIDDEN"});});
  test("contradictory fallback is rejected",async()=>expect(h.deliveryPricing.create(identity(),cityId,{...input,routingFallbackEnabled:false})).rejects.toMatchObject({publicCode:"VALIDATION_FAILED"}));
  test("PAUSED eligible Store routes and produces internal snapshot",async()=>{await activate();h.routingProvider.setResult({distanceMeters:2500.25,durationSeconds:301.5});const result=await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}});expect(result.publicEstimate).toMatchObject({deliveryAvailable:true,distanceSource:"ROUTE",distanceMeters:2500.25,deliveryFee:2000,store:{orderAcceptanceStatus:"PAUSED"}});expect(result.snapshot).toMatchObject({routeDistanceMeters:2500.25,pricingDistanceMeters:2500.25,finalDeliveryFee:2000});});
  test("NoRoute uses exact fallback contract",async()=>{await activate();h.routingProvider.setResult(fakeRoutingError("NO_ROUTE"));const result=await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}});expect(result.publicEstimate).toMatchObject({distanceSource:"STRAIGHT_LINE_FALLBACK",fallbackReason:"NO_ROUTE"});expect(result.snapshot!.pricingDistanceMeters).toBe(result.snapshot!.straightLineDistanceMeters+300);});
  test("transient failure uses provider fallback",async()=>{await activate();h.routingProvider.setResult(fakeRoutingError("TIMEOUT",true));expect((await h.deliveryPricing.estimate(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}})).publicEstimate.fallbackReason).toBe("PROVIDER_FAILURE");});
  test("outside Zone does not invoke provider",async()=>{await activate();const calls=h.routingProvider.calls;const result=await h.deliveryPricing.estimatePublic(customerId,cityId,{storeId,destination:{latitude:35,longitude:46}});expect(result).toMatchObject({deliveryAvailable:false,reason:"ADDRESS_OUTSIDE_DELIVERY_ZONE",deliveryFee:null});expect(h.routingProvider.calls).toBe(calls);});
  test("exactly one destination and owned address are enforced",async()=>{await activate();await expect(h.deliveryPricing.estimate(customerId,cityId,{storeId})).rejects.toMatchObject({publicCode:"VALIDATION_FAILED"});await expect(h.deliveryPricing.estimate(customerId,cityId,{storeId,addressId:crypto.randomUUID(),destination:{latitude:33.3,longitude:44.4}})).rejects.toMatchObject({publicCode:"VALIDATION_FAILED"});await expect(h.deliveryPricing.estimate(customerId,cityId,{storeId,addressId:crypto.randomUUID()})).rejects.toMatchObject({publicCode:"ADDRESS_NOT_FOUND"});});
  test("NoRoute without fallback and maximum distance are HTTP-style domain results",async()=>{await activate({...input,fallbackOnNoRoute:false,maximumDeliveryDistanceMeters:2000});h.routingProvider.setResult(fakeRoutingError("NO_ROUTE"));expect((await h.deliveryPricing.estimatePublic(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}})).reason).toBe("ROUTE_NOT_FOUND");h.routingProvider.setResult({distanceMeters:2001,durationSeconds:1});expect((await h.deliveryPricing.estimatePublic(customerId,cityId,{storeId,destination:{latitude:33.31,longitude:44.41}})).reason).toBe("MAX_DISTANCE_EXCEEDED");});
  test("activation writes cache after commit and audit events are transactional",async()=>{const row=await h.deliveryPricing.create(identity(),cityId,input,"request-create");expect(h.activePricingCache.writes).toBe(0);await h.deliveryPricing.activate(identity(),cityId,row.id,"request-activate");expect(h.activePricingCache.writes).toBe(1);const cached=JSON.parse(h.activePricingCache.values.get(cityId)!);expect(cached).toMatchObject({pricingVersionId:row.id,status:"ACTIVE",cityId});const audits=await h.client<{event_type:string}[]>`select event_type from audit_logs where target_id=${row.id} order by occurred_at`;expect(audits.map(x=>x.event_type)).toEqual(["DELIVERY_PRICING_VERSION_CREATED","DELIVERY_PRICING_VERSION_ACTIVATED"]);});
  test("failed activation publishes neither cache nor success audit",async()=>{const row=await h.deliveryPricing.create(identity(),cityId,input);await h.client`update cities set status='SUSPENDED' where id=${cityId}`;await expect(h.deliveryPricing.activate(identity(),cityId,row.id)).rejects.toMatchObject({publicCode:"CITY_NOT_ACTIVE"});expect(h.activePricingCache.writes).toBe(0);expect((await h.client<{count:number}[]>`select count(*)::int count from audit_logs where event_type='DELIVERY_PRICING_VERSION_ACTIVATED'`)[0]!.count).toBe(0);});
  test("corrupt cache reloads DB and Redis failure safely falls back",async()=>{await activate();h.activePricingCache.values.set(cityId,"{corrupt");const loaded=await h.deliveryPricing.activeForSuper(identity(),cityId);expect(loaded.status).toBe("ACTIVE");expect(JSON.parse(h.activePricingCache.values.get(cityId)!).pricingVersionId).toBe(loaded.pricingVersionId);h.activePricingCache.values.clear();h.activePricingCache.failReads=true;h.activePricingCache.failWrites=true;expect((await h.deliveryPricing.activeForSuper(identity(),cityId)).status).toBe("ACTIVE");});
  test("stale cache fill cannot overwrite newer activation revision",async()=>{const first=await h.deliveryPricing.create(identity(),cityId,input);await h.deliveryPricing.activate(identity(),cityId,first.id);const stale=JSON.parse(h.activePricingCache.values.get(cityId)!);const second=await h.deliveryPricing.create(identity(),cityId,input);await h.deliveryPricing.activate(identity(),cityId,second.id);expect(await h.activePricingCache.writeIfNewer(cityId,stale,21600)).toBeFalse();expect(JSON.parse(h.activePricingCache.values.get(cityId)!).pricingVersionId).toBe(second.id);});
  test("HTTP authorization: SUPER_ADMIN manages while ADMIN reads signed City only",async()=>{
    const password="fixed dashboard password";
    await createStaffAccount(h.auth,h.client,{email:"pricing-super@example.com",password,roles:["SUPER_ADMIN"]});
    await createStaffAccount(h.auth,h.client,{email:"pricing-admin@example.com",password,roles:["ADMIN"],cityId});
    const superToken=(await h.auth.dashboard.login({email:"pricing-super@example.com",password,deviceName:"s",ip:"s",requestId:"s"})).access_token;
    const adminToken=(await h.auth.dashboard.login({email:"pricing-admin@example.com",password,deviceName:"a",ip:"a",requestId:"a"})).access_token;
    const created=await h.app.handle(jsonRequest(`/api/v1/dashboard/cities/${cityId}/delivery-pricing/versions`,{token:superToken,body:input}));
    expect(created.status).toBe(200);
    const createdBody=await created.json() as {id:string};
    expect(createdBody.id).toMatch(/^[0-9a-f-]{36}$/);
    const activation=await h.app.handle(jsonRequest(`/api/v1/dashboard/cities/${cityId}/delivery-pricing/versions/${createdBody.id}/activate`,{token:superToken,method:"POST"}));
    expect(activation.status).toBe(200);
    expect((await h.app.handle(jsonRequest(`/api/v1/dashboard/cities/${cityId}/delivery-pricing/versions`,{token:adminToken,body:input}))).status).toBe(403);
    const activeResponse=await h.app.handle(jsonRequest("/api/v1/dashboard/delivery-pricing/active",{token:adminToken}));
    expect(activeResponse.status).toBe(200);
    expect((await activeResponse.json() as {cityId:string}).cityId).toBe(cityId);
    const document=await (await h.app.handle(new Request("http://localhost/openapi/json"))).json() as {paths:Record<string,unknown>};
    const estimateContract=JSON.stringify(document.paths["/api/v1/mobile/customer/delivery-pricing/estimate"]);
    expect(estimateContract).toContain("pricingVersionId");
    expect(estimateContract).not.toContain('"snapshot":');
  });
});
